export const CONTENT = {
  createdBy: 'OcOewqA7uqVVlVfqY453F8vgcc33',
  createdDate: 1648495716067,
  data: {
    httpRequests: {},
    inputs: [],
    jsCode:
      'var __awaiter=function(e,n,t,r){return new(t||(t=Promise))((function(o,a){function i(e){try{l(r.next(e))}catch(e){a(e)}}function u(e){try{l(r.throw(e))}catch(e){a(e)}}function l(e){var n;e.done?o(e.value):(n=e.value,n instanceof t?n:new t((function(e){e(n)}))).then(i,u)}l((r=r.apply(e,n||[])).next())}))},__generator=function(e,n){var t,r,o,a,i={label:0,sent:function(){if(1&o[0])throw o[1];return o[1]},trys:[],ops:[]};return a={next:u(0),throw:u(1),return:u(2)},"function"==typeof Symbol&&(a[Symbol.iterator]=function(){return this}),a;function u(a){return function(u){return function(a){if(t)throw new TypeError("Generator is already executing.");for(;i;)try{if(t=1,r&&(o=2&a[0]?r.return:a[0]?r.throw||((o=r.return)&&o.call(r),0):r.next)&&!(o=o.call(r,a[1])).done)return o;switch(r=0,o&&(a=[2&a[0],o.value]),a[0]){case 0:case 1:o=a;break;case 4:return i.label++,{value:a[1],done:!1};case 5:i.label++,r=a[1],a=[0];continue;case 7:a=i.ops.pop(),i.trys.pop();continue;default:if(!(o=(o=i.trys).length>0&&o[o.length-1])&&(6===a[0]||2===a[0])){i=0;continue}if(3===a[0]&&(!o||a[1]>o[0]&&a[1]<o[3])){i.label=a[1];break}if(6===a[0]&&i.label<o[1]){i.label=o[1],o=a;break}if(o&&i.label<o[2]){i.label=o[2],i.ops.push(a);break}o[2]&&i.ops.pop(),i.trys.pop();continue}a=n.call(e,i)}catch(e){a=[6,e],r=0}finally{t=o=0}if(5&a[0])throw a[1];return{value:a[0]?a[1]:void 0,done:!0}}([a,u])}}};function main(){return __awaiter(this,void 0,void 0,(function(){return __generator(this,(function(e){return state.a=1234,Builder.isServer,Builder.isBrowser,[2]}))}))}var _virtual_index=main();return _virtual_index',
    title: 'data-bindings',
    blocks: [
      {
        '@type': '@builder.io/sdk:Element',
        '@version': 2,
        id: 'builder-cba9793cfcb247fa9ab4e980fe94ebbb',
        children: [
          {
            '@type': '@builder.io/sdk:Element',
            '@version': 2,
            id: 'builder-ff1edde87ef94d1bba1eb1bd58e303e9',
            component: {
              name: 'Text',
              options: {
                text: "<h3>The text block below has 'state.a' as its value. This page has JS code that sets `state.a = 1234` on mount:</h3>",
              },
            },
            responsiveStyles: {
              large: {
                display: 'flex',
                flexDirection: 'column',
                position: 'relative',
                flexShrink: '0',
                boxSizing: 'border-box',
                marginTop: '20px',
                lineHeight: 'normal',
                height: 'auto',
                textAlign: 'center',
              },
            },
          },
          {
            '@type': '@builder.io/sdk:Element',
            '@version': 2,
            bindings: {
              'component.options.text':
                'var _virtual_index=state.a;return _virtual_index',
            },
            id: 'builder-10ddd88e45f84799821131a3ee9ceff5',
            component: {
              name: 'Text',
              options: { text: 'Enter some text...' },
            },
            responsiveStyles: {
              large: {
                display: 'flex',
                flexDirection: 'column',
                position: 'relative',
                flexShrink: '0',
                boxSizing: 'border-box',
                marginTop: '20px',
                lineHeight: 'normal',
                height: 'auto',
                textAlign: 'center',
              },
            },
          },
        ],
        responsiveStyles: {
          large: {
            display: 'flex',
            flexDirection: 'column',
            position: 'relative',
            flexShrink: '0',
            boxSizing: 'border-box',
            marginTop: '20px',
            height: 'auto',
            paddingBottom: '30px',
          },
        },
      },
      {
        '@type': '@builder.io/sdk:Element',
        '@version': 2,
        layerName: 'Box',
        id: 'builder-e6009621b4604a9589c10750311c983b',
        children: [
          {
            '@type': '@builder.io/sdk:Element',
            '@version': 2,
            id: 'builder-10fe249ccf6a44d3830cc988798599bf',
            component: {
              name: 'Text',
              options: {
                text: '<h3>The text block below has `<span style="color: rgb(0, 0, 0); background-color: rgb(255, 255, 255);">state.article.entry.title</span>` as its value. This page is pulling data from Contentstack under the `article` key:</h3>',
              },
            },
            responsiveStyles: {
              large: {
                display: 'flex',
                flexDirection: 'column',
                position: 'relative',
                flexShrink: '0',
                boxSizing: 'border-box',
                marginTop: '20px',
                lineHeight: 'normal',
                height: 'auto',
                textAlign: 'center',
              },
            },
          },
          {
            '@type': '@builder.io/sdk:Element',
            '@version': 2,
            bindings: {
              'component.options.text':
                'var _virtual_index=state.a;return _virtual_index',
            },
            id: 'builder-26eb0da975d04faaa9fb5e87a5563a04',
            component: {
              name: 'Text',
              options: { text: 'Enter some text...' },
            },
            responsiveStyles: {
              large: {
                display: 'flex',
                flexDirection: 'column',
                position: 'relative',
                flexShrink: '0',
                boxSizing: 'border-box',
                marginTop: '20px',
                lineHeight: 'normal',
                height: 'auto',
                textAlign: 'center',
              },
            },
          },
        ],
        responsiveStyles: {
          large: {
            display: 'none',
            flexDirection: 'column',
            position: 'relative',
            flexShrink: '0',
            boxSizing: 'border-box',
            marginTop: '20px',
            height: 'auto',
            paddingBottom: '30px',
          },
        },
      },
      {
        '@type': '@builder.io/sdk:Element',
        '@version': 2,
        layerName: 'Box',
        id: 'builder-4ad05ed059674a81a42a3d4da100d706',
        children: [
          {
            '@type': '@builder.io/sdk:Element',
            '@version': 2,
            id: 'builder-77c4d7d1b16c4d4b8ab19b080734a3c6',
            component: {
              name: 'Text',
              options: {
                text: '<h3>The text block below `<span style="background-color: rgb(255, 255, 255); color: rgb(0, 0, 0);">state.article2.entry.title</span>` as its value. This page is pulling data from Contentstack under the `article2` key:</h3>',
              },
            },
            responsiveStyles: {
              large: {
                display: 'flex',
                flexDirection: 'column',
                position: 'relative',
                flexShrink: '0',
                boxSizing: 'border-box',
                marginTop: '20px',
                lineHeight: 'normal',
                height: 'auto',
                textAlign: 'center',
              },
            },
          },
          {
            '@type': '@builder.io/sdk:Element',
            '@version': 2,
            bindings: {
              'component.options.text':
                'var _virtual_index=state.article2.entry.title;return _virtual_index',
            },
            id: 'builder-711be594b70c44089ceb71fd54a00fff',
            component: {
              name: 'Text',
              options: { text: 'Enter some text...' },
            },
            responsiveStyles: {
              large: {
                display: 'flex',
                flexDirection: 'column',
                position: 'relative',
                flexShrink: '0',
                boxSizing: 'border-box',
                marginTop: '20px',
                lineHeight: 'normal',
                height: 'auto',
                textAlign: 'center',
              },
            },
          },
        ],
        responsiveStyles: {
          large: {
            display: 'flex',
            flexDirection: 'column',
            position: 'relative',
            flexShrink: '0',
            boxSizing: 'border-box',
            marginTop: '20px',
            height: 'auto',
            paddingBottom: '30px',
          },
        },
      },
      {
        '@type': '@builder.io/sdk:Element',
        '@version': 2,
        id: 'builder-bcff18a6aa3e4015a9be7b6a18478328',
        children: [
          {
            '@type': '@builder.io/sdk:Element',
            '@version': 2,
            id: 'builder-0e660fc97553401ba4800cec4e850928',
            component: {
              name: 'Text',
              options: {
                text: '<span style="display: block;" class="builder-heading-3">The text block below repeats for every item in `state.article`, which is Contentstack data under the `article` key:</span>',
              },
            },
            responsiveStyles: {
              large: {
                display: 'flex',
                flexDirection: 'column',
                position: 'relative',
                flexShrink: '0',
                boxSizing: 'border-box',
                marginTop: '20px',
                lineHeight: 'normal',
                height: 'auto',
                textAlign: 'center',
              },
            },
          },
          {
            '@type': '@builder.io/sdk:Element',
            '@version': 2,
            repeat: { collection: 'state.article.entries' },
            id: 'builder-f15a1661580a429f8e4b4612e3911c86',
            children: [
              {
                '@type': '@builder.io/sdk:Element',
                '@version': 2,
                bindings: {
                  'component.options.text':
                    'var _virtual_index=state.entriesItem.title;return _virtual_index',
                },
                repeat: { collection: '' },
                id: 'builder-3d4ec69b532340d48e2f11bf1f41dcac',
                component: {
                  name: 'Text',
                  options: { text: 'Enter some text...' },
                },
                responsiveStyles: {
                  large: {
                    display: 'flex',
                    flexDirection: 'column',
                    position: 'relative',
                    flexShrink: '0',
                    boxSizing: 'border-box',
                    marginTop: '20px',
                    lineHeight: 'normal',
                    height: 'auto',
                    textAlign: 'center',
                  },
                },
              },
              {
                '@type': '@builder.io/sdk:Element',
                '@version': 2,
                bindings: {
                  'component.options.image':
                    'var _virtual_index=state.entriesItem.thumbnail.url;return _virtual_index',
                },
                id: 'builder-0ed920c6e50d46ca9769a5b511e5f715',
                component: {
                  name: 'Image',
                  options: {
                    image:
                      'https://cdn.builder.io/api/v1/image/assets%2Fpwgjf0RoYWbdnJSbpBAjXNRMe9F2%2Ffb27a7c790324294af8be1c35fe30f4d?width=100',
                    backgroundSize: 'cover',
                    backgroundPosition: 'center',
                    lazy: false,
                    fitContent: true,
                    aspectRatio: 0.7041,
                    sizes:
                      '(max-width: 638px) 16vw, (max-width: 998px) 11vw, 8vw',
                  },
                },
                responsiveStyles: {
                  large: {
                    display: 'flex',
                    flexDirection: 'column',
                    position: 'relative',
                    flexShrink: '0',
                    boxSizing: 'border-box',
                    marginTop: '20px',
                    width: '100px',
                    minHeight: '20px',
                    minWidth: '20px',
                    overflow: 'hidden',
                    height: '100px',
                    marginLeft: 'auto',
                    marginRight: 'auto',
                  },
                },
              },
            ],
            responsiveStyles: {
              large: {
                display: 'flex',
                flexDirection: 'column',
                position: 'relative',
                flexShrink: '0',
                boxSizing: 'border-box',
                marginTop: '20px',
                height: 'auto',
                paddingBottom: '30px',
              },
            },
          },
        ],
        responsiveStyles: {
          large: {
            display: 'flex',
            flexDirection: 'column',
            position: 'relative',
            flexShrink: '0',
            boxSizing: 'border-box',
            marginTop: '20px',
            height: 'auto',
            paddingBottom: '30px',
          },
        },
      },
      {
        id: 'builder-pixel-77endcp01wc',
        '@type': '@builder.io/sdk:Element',
        tagName: 'img',
        properties: {
          src: 'https://cdn.builder.io/api/v1/pixel?apiKey=f1a790f8c3204b3b8c5c1795aeac4660',
          role: 'presentation',
          width: '0',
          height: '0',
        },
        responsiveStyles: {
          large: {
            height: '0',
            width: '0',
            display: 'inline-block',
            opacity: '0',
            overflow: 'hidden',
            pointerEvents: 'none',
          },
        },
      },
    ],
    url: '/data-bindings',
    state: {
      deviceSize: 'large',
      location: {
        pathname: '/data-bindings',
        path: ['data-bindings'],
        query: {},
      },
      a: 1234,
      article2: {
        entry: {
          _version: 1,
          locale: 'en-us',
          uid: 'blt428b7a6a431e4d82',
          ACL: {},
          _in_progress: false,
          body: '<p></p><ul><li><strong>Celebrating its fourth year, the 2021 Hot Wheels™ Legends Tour presented by Mobil 1 will expand the global search for the ultimate life-size custom car to be immortalized as a 1:64 Hot Wheels die-cast model.</strong></li><li><strong>Kicking off in April, the Hot Wheels Legends Tour is expected to receive 10,000+ entrants across 14 countries and 5 continents.</strong></li><li><strong>The Tour will culminate in November with a global grand finale event, crowning the next Hot Wheels Garage of Legends™ inductee.</strong></li></ul><p><br/><br/><strong>EL SEGUNDO, Calif., March 18, 2021</strong>— Today, the 2021 Hot Wheels Legends Tour presented by Mobil 1 is officially open for fan car submissions. Back for its fourth year, the 2021 Hot Wheels Legends Tour will continue the Hot Wheels tradition of offering global fans the unique opportunity to have their one-of-a-kind life-size car creations forever immortalized as the next Hot Wheels Garage of Legends 1:64 die-cast toy.<br/><br/><br/>In true challenger spirit, this year’s Hot Wheels Legends Tour competition is geared up to be bigger than ever before. With stops spanning 14 countries and 5 continents, the 2021 showdown will feature both live and virtual events kicking off in April with livestream stops in New Zealand (April 15), Australia (April 22), and the U.S. and Canada (April 29).<br/><br/><br/>Dates for future stops will be announced soon, and fans may register or learn more about the Hot Wheels Legends Tour by visiting&nbsp;<a href="https://hotwheels.mattel.com/explore/en/legends-tour">www.HotWheels.com/Legends</a><strong>.&nbsp;</strong>Livestreams will be available to view on the Hot Wheels Facebook page, on Walmart.com and through automotive media partners in specific countries. Live events will be returning to U.S.-based Walmart stores this summer.<br/><br/><br/>“Finding time to build isn’t always easy, but with many spending more time at home in the garage over the past year, we expect to see so many more passion-project submissions for the 2021 Hot Wheels Legends Tour,” said Ted Wu, Global Head of Hot Wheels Design at Mattel. “Last year, we received more than 10,000 entries, and with the added international stops, this year’s competition is expected to be more impressive with more vehicle variety than ever.”<br/><br/></p><img src="https://s7d1.scene7.com/is/image/mattelsites/hw-3-1230x692-not-cropped?wid=1000&hei=563&dpr=off" width="100"/><br/><p>In partnership with Mobil 1, Hot Wheels Legends Tour stops will have regional winners plus a Mobil 1 Fan Favorite, which will then be entered into the semi-final rounds representing the U.S. and global regions, yielding 10 finalists. The Tour will culminate at a grand finale event in November where there will be one custom car creation inducted into the Hot Wheels Garage of Legends and honored as the next Hot Wheels&nbsp;die-cast toy sold around the world.</p><p><br/><br/>In addition to being immortalized as a 1:64 die-cast toy, previous Legends Tour winners, including the 2018 winning 2JetZ™ and the 2019 winning classic coupe titled “The Nash,” will soon be available for purchase and play through the Forza™ Horizon 4 video game through the Hot Wheels Legends Car Pack on Xbox, Windows 10, iOS and Android devices.<br/><br/><br/>Since its launch in 2018 to celebrate Hot Wheels 50th&nbsp;Anniversary, the Hot Wheels Legends Tour has grown from an American-based series of local Walmart events across the United States to the world’s largest travelling car show, bringing in builders and automotive fans through both virtual and live events. In 2021 the Hot Wheels Legends Tour will be featuring stops in a dozen new countries, including Australia with Big W, New Zealand with The Warehouse and more.<br/><br/><br/>“The Mobil 1 brand is excited to again support the Hot Wheels Legends Tour,” said Ryan Allen, Senior Shopper Marketing Advisor, ExxonMobil. “We’re looking forward to continuing our partnership with Hot Wheels to showcase incredible cars, built by incredible people. We are eager to see the return of the Mobil 1 Fan Favorite, and encourage fans to vote for their favorite car at each stop to get it to the final. We are always thrilled to see there are fans who love cars as much as we do!”<br/><br/><br/>Conceived in 1968 by an innovator, a rocket scientist and a car designer, Hot Wheels 1:64 scale die-cast cars were designed to look awesome and perform like no other toy. Five decades later, Hot Wheels is the number one selling toy in the world* with more than 16.5 cars sold every second. The brand has evolved from a simple, yet beloved, toy car with orange track system into a global franchise powerhouse that offers fans of all ages multi-channel play experiences.<br/><br/><br/>*Source: The NPD Group/Retail Tracking Service<br/><br/><br/><br/><strong>About Mattel</strong><br/><br/>Mattel is a leading global toy company and owner of one of the strongest catalogs of children’s and family entertainment franchises in the world. We create innovative products and experiences that inspire, entertain and develop children through play. We engage consumers through our portfolio of iconic brands, including Barbie®, Hot Wheels®, Fisher-Price®, American Girl®, Thomas & Friends™, UNO® and MEGA®, as well as other popular intellectual properties that we own or license in partnership with global entertainment companies. Our offerings include film and television content, gaming, music and live events. We operate in 35 locations and our products are available in more than 150 countries in collaboration with the world’s leading retail and e-commerce companies. Since its founding in 1945, Mattel is proud to be a trusted partner in empowering children to explore the wonder of childhood and reach their full potential.<br/><br/><br/><strong>About Mobil 1</strong><br/><br/>Mobil 1™ motor oil is the world\'s leading brand of synthetic motor oil. Our advanced technology allows Mobil 1 motor oils to meet or exceed some of the industry’s toughest standards and to provide exceptional protection under even extreme driving conditions. Mobil 1 motor oil is designed to help protect critical engine parts,&nbsp;maximize engine performance, and extend engine life.&nbsp;For more information, visit us online at&nbsp;<a href="https://urldefense.com/v3/__http:/www.mobil1.us__;!!Hd5UnLY!gR66VEr80--33wdHbEVkgZMgAGAZYx914-oTiwTE5_og2eTHtSljeoEaWCElX1jjKciruw$">www.mobil1.us</a>&nbsp;or and follow @Mobil1 on Facebook, Instagram and Twitter.</p>',
          category: ['Brand News'],
          created_at: '2022-03-16T17:29:13.984Z',
          created_by: 'blt1414fb1755930b78',
          date: '2021-03-18',
          download_media: [
            {
              uid: 'blt30b543516a3a2f4b',
              created_by: 'blt1414fb1755930b78',
              updated_by: 'blt1414fb1755930b78',
              created_at: '2022-03-16T17:28:12.229Z',
              updated_at: '2022-03-16T17:28:12.229Z',
              content_type: 'image/jpeg',
              file_size: '74326',
              filename: 'hw-3-1230x820.jpg',
              title: 'hw-3-1230x820.jpg',
              ACL: {},
              _version: 1,
              parent_uid: null,
              is_dir: false,
              tags: [],
              publish_details: {
                environment: 'blta57963b4c954ce6c',
                locale: 'en-us',
                time: '2022-03-16T17:30:32.702Z',
                user: 'blt1414fb1755930b78',
              },
              url: 'https://images.contentstack.io/v3/assets/bltc12136c3b9f23503/blt30b543516a3a2f4b/62321e2cf036fb5c3dd0b00f/hw-3-1230x820.jpg',
            },
            {
              uid: 'blt706ba92d32c9d9b6',
              created_by: 'blt1414fb1755930b78',
              updated_by: 'blt1414fb1755930b78',
              created_at: '2022-03-16T17:28:12.540Z',
              updated_at: '2022-03-16T17:28:12.540Z',
              content_type: 'image/jpeg',
              file_size: '92435',
              filename: 'hw-1-v4-v1-1200x800.jpg',
              title: 'hw-1-v4-v1-1200x800.jpg',
              ACL: {},
              _version: 1,
              parent_uid: null,
              is_dir: false,
              tags: [],
              publish_details: {
                environment: 'blta57963b4c954ce6c',
                locale: 'en-us',
                time: '2022-03-16T17:30:32.729Z',
                user: 'blt1414fb1755930b78',
              },
              url: 'https://images.contentstack.io/v3/assets/bltc12136c3b9f23503/blt706ba92d32c9d9b6/62321e2cdb05116a6e694a37/hw-1-v4-v1-1200x800.jpg',
            },
            {
              uid: 'bltefbb613db32979a2',
              created_by: 'blt1414fb1755930b78',
              updated_by: 'blt1414fb1755930b78',
              created_at: '2022-03-16T17:28:13.073Z',
              updated_at: '2022-03-16T17:28:13.073Z',
              content_type: 'image/jpeg',
              file_size: '86663',
              filename: 'hw-2-v6-1200x800.jpg',
              title: 'hw-2-v6-1200x800.jpg',
              ACL: {},
              _version: 1,
              parent_uid: null,
              is_dir: false,
              tags: [],
              publish_details: {
                environment: 'blta57963b4c954ce6c',
                locale: 'en-us',
                time: '2022-03-16T17:30:32.750Z',
                user: 'blt1414fb1755930b78',
              },
              url: 'https://images.contentstack.io/v3/assets/bltc12136c3b9f23503/bltefbb613db32979a2/62321e2d0f49f75a7c667d18/hw-2-v6-1200x800.jpg',
            },
          ],
          handle:
            'the-hot-wheels-legends-tour-is-back-with-global-hunt-for-next-fan-made-custom-hot-wheels-die-cast-toy',
          seo_description:
            'EL SEGUNDO, Calif., March 18, 2021— Today, the 2021 Hot Wheels Legends Tour presented by Mobil 1 is officially open for fan car submissions. ',
          seo_title:
            'The Hot Wheels™ Legends Tour is Back with Global Hunt for Next Fan-Made Custom Hot Wheels® Die-Cast Toy | Mattel, Inc.',
          tags: [],
          thumbnail: {
            uid: 'blta40640f5ed86acc0',
            created_by: 'blt1414fb1755930b78',
            updated_by: 'blt1414fb1755930b78',
            created_at: '2022-03-16T17:28:00.215Z',
            updated_at: '2022-03-16T17:28:00.215Z',
            content_type: 'image/jpeg',
            file_size: '195931',
            filename: 'thumbnail-hw-2-v6-560x420.jpg',
            title: 'thumbnail-hw-2-v6-560x420.jpg',
            ACL: {},
            _version: 1,
            parent_uid: null,
            is_dir: false,
            tags: [],
            publish_details: {
              environment: 'blta57963b4c954ce6c',
              locale: 'en-us',
              time: '2022-03-16T17:30:32.776Z',
              user: 'blt1414fb1755930b78',
            },
            url: 'https://images.contentstack.io/v3/assets/bltc12136c3b9f23503/blta40640f5ed86acc0/62321e20f036fb5c3dd0b00b/thumbnail-hw-2-v6-560x420.jpg',
          },
          title:
            'The Hot Wheels™ Legends Tour is Back with Global Hunt for Next Fan-Made Custom Hot Wheels® Die-Cast Toy',
          updated_at: '2022-03-16T17:29:13.984Z',
          updated_by: 'blt1414fb1755930b78',
          publish_details: {
            environment: 'blta57963b4c954ce6c',
            locale: 'en-us',
            time: '2022-03-16T17:30:32.800Z',
            user: 'blt1414fb1755930b78',
          },
        },
      },
      article: {
        entries: [
          {
            _version: 8,
            locale: 'en-us',
            uid: 'bltaaf2fd0cb242fb13',
            _in_progress: false,
            body: '<p style="text-align: left;"><span style="color: black;"><em></em></span><span style="color: black;"><strong>EL SEGUNDO, Calif., – July 18, 2022 – </strong></span><span style="color: black;">Mattel, Inc. (NASDAQ: MAT) announced today that its all-new animated children’s series </span><span style="color: black;"><em>Deepa & Anoop </em></span><span style="color: black;">will debut on Netflix on August 15, 2022. Created by acclaimed Bollywood animator Munjal Shroff (</span><span style="color: black;"><em>Shortcut Safari</em></span><span style="color: black;">), accomplished writer Lisa Goldman (</span><span style="color: black;"><em>Dragon Tales</em></span><span style="color: black;">), and award-winning producer Heather Kenyon (</span><span style="color: black;"><em>Doki Adventures</em></span><span style="color: black;">) with production services provided by award-winning Kickstart Entertainment (StarBeam), </span><span style="color: black;"><em>Deepa & Anoop</em></span><span style="color: black;"> is Mattel Television’s first original series based on original intellectual property.</span></p><p><span style="color: black;">The colorful, music-driven series follows the adventures of seven-year-old Deepa and her best friend Anoop, a half-ton color-changing baby elephant. The dynamic duo, self-appointed “concierges of fun,” makes everything bigger, grander and more wonderful for guests at Mango Manor, the bed and breakfast run by Deepa’s multigenerational family. With a Bollywood number in every episode, Deepa creates music, merriment and mischief while working with the rambunctious Anoop to solve the simplest of problems with the most imaginative of solutions.</span></p><p><span style="color: black;">With a strong focus on the authenticity of Deepa’s Indian heritage, </span><span style="color: black;"><em>Deepa & Anoop</em></span><span style="color: black;"> includes 18 original song and dance performances, several of which are presented in the Bollywood tradition. The main cast is voiced by actors of Indian descent, including Pavan Bharaj as Deepa, Veena Sood (</span><span style="color: black;"><em>The Twilight Zone</em></span><span style="color: black;">) as Naani-ji, and Ana Sani (</span><span style="color: black;"><em>The Magic School Bus</em></span><span style="color: black;">) as Mama.</span></p><p><span style="color: black;">“While Mattel is well-known for developing entertainment content based on our fan-favorite brands, we’re excited to partner with Netflix to bring audiences a heartwarming, all-new series based on original IP,” said Fred Soulie, Senior Vice President and General Manager at Mattel Television. </span><span style="color: rgb(36, 36, 36);">“Later this summer, fans will be delighted as Deepa and her best friend Anoop take on exciting challenges and lead colorful musical numbers that illustrate the importance of friendship. </span><span style="color: rgb(36, 36, 36);"><em>Deepa & Anoop </em></span><span style="color: rgb(36, 36, 36);">is sure to make an impact on audiences globally.”</span></p><p><span style="color: black;">In addition to this original series, Mattel continues to expand its roster of beloved brands well beyond the toy aisle and into the television and film space. More than 30 of Mattel’s beloved brands—including Barbie, Masters of the Universe, Thomas & Friends, Polly Pocket, Monster High, Fireman Sam, Bob the Builder, and Hot Wheels, to name a few—have come to life in various animated series, movies, specials and digital short-form. </span><span style="color: black;"><em>Deepa & Anoop, </em></span><span style="color: black;">however</span><span style="color: black;"><em>, </em></span><span style="color: black;">marks Mattel\'s first-ever animated series based entirely on an original story and original characters.</span></p><p><span style="color: black;">“We have been lucky to work alongside best-in-class advisors and consultants during every stage of </span><span style="color: black;"><em>Deepa & Anoop’s </em></span><span style="color: black;">development,” said Christopher Keenan, Senior Vice President of Creative at Mattel Television. “Our hope is that young audiences around the world will find this heartwarming series as authentic as they do relatable. We could not be more proud or excited that </span><span style="color: black;"><em>Deepa & Anoop </em></span><span style="color: black;">is Mattel’s first original series based on all-new IP.”</span></p><p><span style="color: black;">The debut season of </span><span style="color: black;"><em>Deepa & Anoop</em></span><span style="color: black;"> includes 11 30-minute episodes and two 22-minute specials. </span><span style="color: black;"><em>Deepa & Anoop </em></span><span style="color: black;">is executive produced by Mattel Television\'s Fred Soulie and Christopher Keenan.</span></p><p><span style="color: black;"><strong>About Mattel</strong></span></p><p><span style="color: black;">Mattel is a leading global toy company and owner of one of the strongest catalogs of children’s and family entertainment franchises in the world. We create innovative products and experiences that inspire, entertain, and develop children through play. We engage consumers through our portfolio of iconic brands, including Barbie®, Hot Wheels®, Fisher-Price®, American Girl®, Thomas & Friends®, UNO®,&nbsp;and MEGA®, as well as other popular intellectual properties that we own or license in partnership with global entertainment companies. Our offerings include film and television content, gaming and digital experiences, music,&nbsp;and live events. We operate ­in 35 locations and our products are available in more than 150 countries in collaboration with the world’s leading retail and ecommerce companies. Since its founding in 1945, Mattel is proud to be a trusted partner in empowering children&nbsp;to explore the wonder of childhood and reach their full potential. Visit us online at </span><a href="https://www.mattel.com/" target="_blank">mattel.com</a><span style="color: black;">.</span></p><p><span style="color: black;"><strong>Press Contacts</strong></span></p><p><span style="color: black;">Niki Kazakos</span><a href="mailto:Niki.Kazakos@mattel.com" target="_self"><br/>Niki.Kazakos@mattel.com</a></p><p><span style="color: black;">Casey McDonald<br/></span><a href="mailto:Casey.Mcdonald@mattel.com" target="_self">Casey.Mcdonald@mattel.com</a></p>',
            category: ['Brand News'],
            created_at: '2022-07-19T03:06:21.165Z',
            created_by: 'blt11a963c080527e88',
            date: '2022-07-18',
            download_media: [
              {
                _version: 1,
                is_dir: false,
                uid: 'bltcbc064cb09c2814f',
                ACL: {},
                content_type: 'image/jpeg',
                created_at: '2022-07-19T03:04:20.992Z',
                created_by: 'blt11a963c080527e88',
                file_size: '502159',
                filename: '20220719-netflix-deepa-anoop-download-1440x810.jpg',
                parent_uid: 'blte7b2ad18a4d449a0',
                tags: [],
                title: '20220719-netflix-deepa-anoop-download-1440x810.jpg',
                updated_at: '2022-07-19T03:04:20.992Z',
                updated_by: 'blt11a963c080527e88',
                publish_details: {
                  environment: 'blta57963b4c954ce6c',
                  locale: 'en-us',
                  time: '2022-07-19T03:04:27.442Z',
                  user: 'blt11a963c080527e88',
                },
                url: 'https://images.contentstack.io/v3/assets/bltc12136c3b9f23503/bltcbc064cb09c2814f/62d61f3427582a3696ad5f50/20220719-netflix-deepa-anoop-download-1440x810.jpg',
              },
            ],
            excerpt: '',
            handle:
              'mattel-to-premiere-all-new-animated-preschool-series-deepa-and-anoop-on-august-15',
            seo_description:
              'Music-Driven Series Marks Mattel’s First Animated Series Based on Original Intellectual Property',
            seo_title:
              'Mattel to Premiere All-New Animated Preschool Series Deepa & Anoop on August 15',
            tags: [],
            thumbnail: {
              _version: 1,
              is_dir: false,
              uid: 'bltcbc064cb09c2814f',
              ACL: {},
              content_type: 'image/jpeg',
              created_at: '2022-07-19T03:04:20.992Z',
              created_by: 'blt11a963c080527e88',
              file_size: '502159',
              filename: '20220719-netflix-deepa-anoop-download-1440x810.jpg',
              parent_uid: 'blte7b2ad18a4d449a0',
              tags: [],
              title: '20220719-netflix-deepa-anoop-download-1440x810.jpg',
              updated_at: '2022-07-19T03:04:20.992Z',
              updated_by: 'blt11a963c080527e88',
              publish_details: {
                environment: 'blta57963b4c954ce6c',
                locale: 'en-us',
                time: '2022-07-19T03:04:27.442Z',
                user: 'blt11a963c080527e88',
              },
              url: 'https://images.contentstack.io/v3/assets/bltc12136c3b9f23503/bltcbc064cb09c2814f/62d61f3427582a3696ad5f50/20220719-netflix-deepa-anoop-download-1440x810.jpg',
            },
            title:
              'Mattel to Premiere All-New Animated Preschool Series Deepa & Anoop on August 15',
            updated_at: '2022-08-15T20:12:25.954Z',
            updated_by: 'bltd78815454ae5df3d',
            publish_details: {
              environment: 'blta57963b4c954ce6c',
              locale: 'en-us',
              time: '2022-08-15T20:12:34.137Z',
              user: 'bltd78815454ae5df3d',
            },
            ACL: {},
          },
          {
            _version: 26,
            locale: 'en-us',
            uid: 'blt5ecf4981a7b5823c',
            _in_progress: false,
            body: '<p><span style="color: black;"><em>By Amy Thompson, EVP and Chief People Officer, Mattel</em></span><span style="color: black;"> –&nbsp;</span></p><p><span style="color: black;">At Mattel, our purpose is to empower the next generation to explore the wonder of childhood and reach their full potential. The incredible work of our employees is central to achieving this purpose – from the positive culture they create to the innovative ideas they bring forward.</span></p><p><span style="color: black;"></span><span style="color: black;">This is why we are thrilled to share that for the second year in a row, Mattel was </span><span style="color: black;"><strong>Certified™ by Great Place to Work</strong></span><span style="color: black;"><strong>®</strong> and recognized as one of </span><span style="color: black;"><strong>Fast Company’s 100 Best Workplaces for Innovators.</strong></span><span style="color: black;"><u></u></span></p><p><span style="color: black;"><strong>Great Place to Work</strong></span></p><p><span style="color: black;">Great Place to Work Certification is the global benchmark for identifying and recognizing outstanding employee experience. It is the only recognition based entirely on what employees report about their workplace experience – specifically, how consistently they experience a high-trust workplace.</span><span style="color: black;"></span></p><p><span style="color: black;">We are proud to share that 88%&nbsp;of&nbsp;our employees said Mattel is a a great place to work,&nbsp;compared to 57% of employees at a typical U.S. based company.</span></p><p><span style="color: black;">At Mattel, we are at our best when every member of our team feels respected, included and heard – when everyone can show up as themselves and do their best work. Our entire team plays a role in this. Thank you to our employees for fostering a culture of belonging and creating an environment where we all can thrive.</span><span style="color: black;"></span></p><p><span style="color: black;">You can learn more about what our employees have&nbsp;to say about Mattel&nbsp;</span><a href="https://www.greatplacetowork.com/certified-company/1000973" target="_blank">here</a><span style="color: black;"><em>.</em></span></p><p><span style="color: black;"><strong>Fast Company’s 100 Best Workplaces for Innovators</strong></span></p><p><span style="color: black;">This year’s recognition, developed by Fast Company in collaboration with Accenture, honors organizations and businesses across a variety of industries that demonstrate a steadfast commitment to encouraging innovation at all levels.</span></p><p><span style="color: black;">Innovation at every level has been a hallmark of Mattel since its founding, and we strongly believe that a good idea can come from anyone, anywhere. No matter where you work in the organization, you can always make a difference and have real impact. We welcome fresh ideas and value new initiatives that challenge conventional thinking.</span></p><p><span style="color: black;">We’re excited to share that this year Mattel ranked No. 23 on </span><a href="https://www.fastcompany.com/best-workplaces-for-innovators/list" target="_blank">Fast Company’s 100 Best Workplaces for Innovators</a><span style="color: black;"> list for continuing to drive growth and innovation throughout the organization – from our products and experiences to our people.</span></p><p><span style="color: black;">We are so honored to receive these recognitions from Great Place to Work and Fast Company once again this year. They are a meaningful reflection of our workplace culture and the achievements of our entire organization.</span></p><p><span style="color: black;">Congratulations to everyone at Mattel!</span></p>',
            category: ['Corporate News'],
            created_at: '2022-08-02T00:32:08.785Z',
            created_by: 'blt11a963c080527e88',
            date: '2022-08-02',
            download_media: [
              {
                _version: 1,
                is_dir: false,
                uid: 'blt5f173f42369f15f4',
                ACL: {},
                content_type: 'image/jpeg',
                created_at: '2022-08-02T01:14:20.336Z',
                created_by: 'blt11a963c080527e88',
                file_size: '158988',
                filename: '0802-amy-post-bptw-fc_832x650.jpg',
                parent_uid: 'bltb2ede58622f3fa98',
                tags: [],
                title: '0802-amy-post-bptw-fc_832x650.jpg',
                updated_at: '2022-08-02T01:14:20.336Z',
                updated_by: 'blt11a963c080527e88',
                publish_details: {
                  environment: 'blta57963b4c954ce6c',
                  locale: 'en-us',
                  time: '2022-08-02T19:29:20.065Z',
                  user: 'blt11a963c080527e88',
                },
                url: 'https://images.contentstack.io/v3/assets/bltc12136c3b9f23503/blt5f173f42369f15f4/62e87a6ca30ae37191c633d9/0802-amy-post-bptw-fc_832x650.jpg',
              },
            ],
            excerpt: '',
            handle:
              'mattel-certified-by-great-place-to-work-and-named-to-fast-companys-list-of-100-best-workplaces-for-innovators',
            seo_description:
              'By Amy Thompson, EVP and Chief People Officer, Mattel',
            seo_title:
              'Mattel Certified by Great Place to Work and Named to Fast Company’s List of 100 Best Workplaces for Innovators',
            tags: [],
            thumbnail: {
              _version: 1,
              is_dir: false,
              uid: 'blt1fd18f7daf2fd5ef',
              ACL: {},
              content_type: 'image/jpeg',
              created_at: '2022-08-02T19:29:13.871Z',
              created_by: 'blt11a963c080527e88',
              file_size: '161720',
              filename: '0802-amy-post-bptw-fc_900x900.jpg',
              parent_uid: 'bltb2ede58622f3fa98',
              tags: [],
              title: '0802-amy-post-bptw-fc_900x900.jpg',
              updated_at: '2022-08-02T19:29:13.871Z',
              updated_by: 'blt11a963c080527e88',
              publish_details: {
                environment: 'blta57963b4c954ce6c',
                locale: 'en-us',
                time: '2022-08-02T19:29:20.090Z',
                user: 'blt11a963c080527e88',
              },
              url: 'https://images.contentstack.io/v3/assets/bltc12136c3b9f23503/blt1fd18f7daf2fd5ef/62e97b09e71af410b83bea11/0802-amy-post-bptw-fc_900x900.jpg',
            },
            title:
              'Mattel Certified by Great Place to Work and Named to Fast Company’s List of 100 Best Workplaces for Innovators',
            updated_at: '2022-08-02T19:46:55.881Z',
            updated_by: 'blt11a963c080527e88',
            publish_details: {
              environment: 'blta57963b4c954ce6c',
              locale: 'en-us',
              time: '2022-08-02T19:47:00.218Z',
              user: 'blt11a963c080527e88',
            },
            ACL: {},
          },
        ],
      },
    },
  },
  id: '6253dc59c0d94956a275910e82a388aa',
  lastUpdatedBy: 'OcOewqA7uqVVlVfqY453F8vgcc33',
  meta: {
    dataSources: [
      {
        dataPluginName: 'Contentstack',
        options: { entry: 'blt428b7a6a431e4d82', limit: 10 },
        propertyName: 'article2',
        resourceId: 'article',
        resourceName: 'article',
      },
      {
        dataPluginName: 'Contentstack',
        options: { limit: 2 },
        propertyName: 'article',
        resourceId: 'article',
        resourceName: 'article',
      },
    ],
    hasLinks: false,
    kind: 'page',
    lastPreviewUrl:
      'http://localhost:3000/data-bindings?builder.space=f1a790f8c3204b3b8c5c1795aeac4660&builder.cachebust=true&builder.preview=page&builder.noCache=true&__builder_editing__=true&builder.overrides.page=6253dc59c0d94956a275910e82a388aa&builder.overrides.6253dc59c0d94956a275910e82a388aa=6253dc59c0d94956a275910e82a388aa&builder.overrides.page:/data-bindings=6253dc59c0d94956a275910e82a388aa',
    needsHydration: false,
  },
  modelId: '240a12053d674735ac2a384dcdc561b5',
  name: 'data-bindings',
  published: 'published',
  query: [
    {
      '@type': '@builder.io/core:Query',
      operator: 'is',
      property: 'urlPath',
      value: '/data-bindings',
    },
  ],
  testRatio: 1,
  variations: {},
  lastUpdated: 1657661730161,
  screenshot:
    'https://cdn.builder.io/api/v1/image/assets%2Ff1a790f8c3204b3b8c5c1795aeac4660%2Fb63148d28c374f489446eb29b5f2225e',
  firstPublished: 1649346870381,
  rev: 'axosvduxjn6',
};
