export const CUSTOM_COMPONENTS_NOWRAP = {
  ownerId: 'ad30f9a246614faaa6a03374f83554c9',
  lastUpdateBy: null,
  createdDate: 1729921094181,
  id: '2a94e13a7d744257bb62cca35ab1b44d',
  '@version': 4,
  name: 'angular-no-wrap',
  modelId: '17c6065109ef4062ba083f5741f4ee6a',
  published: 'draft',
  meta: {
    lastPreviewUrl:
      'http://localhost:4200/angular-no-wrap?builder.space=ad30f9a246614faaa6a03374f83554c9&builder.user.permissions=read%2Ccreate%2Cpublish%2CeditCode%2CeditDesigns%2Cadmin%2CeditLayouts%2CeditLayers&builder.user.role.name=Admin&builder.user.role.id=admin&builder.cachebust=true&builder.preview=page&builder.noCache=true&builder.allowTextEdit=true&__builder_editing__=true&builder.overrides.page=2a94e13a7d744257bb62cca35ab1b44d&builder.overrides.2a94e13a7d744257bb62cca35ab1b44d=2a94e13a7d744257bb62cca35ab1b44d&builder.overrides.page:/angular-no-wrap=2a94e13a7d744257bb62cca35ab1b44d&builder.options.locale=Default',
    componentsUsed: {
      CustomButton: 6,
      CustomCard: 3,
      CustomCardTitle: 3,
      CustomCardFooter: 3,
      CustomCardContent: 3,
    },
    hasLinks: false,
    kind: 'page',
  },
  priority: -760,
  query: [
    {
      '@type': '@builder.io/core:Query',
      property: 'urlPath',
      operator: 'is',
      value: '/angular-no-wrap',
    },
  ],
  data: {
    tsCode: 'state.count = 1',
    title: 'angular-no-wrap',
    themeId: false,
    jsCode: 'var _virtual_index=state.count=1;return _virtual_index',
    inputs: [],
    blocks: [
      {
        '@type': '@builder.io/sdk:Element',
        '@version': 2,
        id: 'builder-341c0f3ab2024f009df1edd609a9c906',
        component: { name: 'Text', options: { text: '<b>CUSTOM BUTTONS (noWrap = true)</b>' } },
        responsiveStyles: {
          large: {
            display: 'flex',
            flexDirection: 'column',
            position: 'relative',
            flexShrink: '0',
            boxSizing: 'border-box',
            marginTop: '20px',
            lineHeight: 'normal',
            height: 'auto',
            fontSize: '40px',
          },
        },
      },
      {
        '@type': '@builder.io/sdk:Element',
        '@version': 2,
        actions: { click: 'var _virtual_index=state.count=state.count+1;return _virtual_index' },
        code: { actions: { click: 'state.count = state.count + 1;\n' } },
        id: 'builder-eb36e02833d74062bc35402ef39a4e22',
        meta: {
          eventActions: {
            click: [
              {
                '@type': '@builder.io/core:Action',
                action: '@builder.io:customCode',
                options: { code: 'state.count = state.count + 1' },
              },
            ],
          },
        },
        component: { name: 'CustomButton', options: {} },
        children: [
          {
            '@type': '@builder.io/sdk:Element',
            '@version': 2,
            id: 'builder-d47fc1ef4a52477f9a74c8b10ee95e81',
            component: { name: 'Text', options: { text: 'increment' } },
            responsiveStyles: {
              large: {
                display: 'flex',
                flexDirection: 'column',
                position: 'relative',
                flexShrink: '0',
                boxSizing: 'border-box',
                marginTop: '0px',
                lineHeight: 'normal',
                height: 'auto',
                fontSize: '16px',
              },
            },
          },
        ],
        responsiveStyles: {
          large: {
            display: 'flex',
            flexDirection: 'column',
            position: 'relative',
            flexShrink: '0',
            boxSizing: 'border-box',
            marginTop: '20px',
            backgroundColor: 'rgba(255, 255, 255, 1)',
            paddingTop: '10px',
            paddingBottom: '10px',
            paddingLeft: '20px',
            paddingRight: '20px',
          },
        },
      },
      {
        '@type': '@builder.io/sdk:Element',
        '@version': 2,
        id: 'builder-ae5e362de95f47cb90176d86630048bb',
        component: { name: 'Text', options: { text: 'Count: {{state.count}}' } },
        responsiveStyles: {
          large: {
            display: 'flex',
            flexDirection: 'column',
            position: 'relative',
            flexShrink: '0',
            boxSizing: 'border-box',
            marginTop: '20px',
            lineHeight: 'normal',
            height: 'auto',
          },
        },
      },
      {
        '@type': '@builder.io/sdk:Element',
        '@version': 2,
        actions: { click: 'var _virtual_index=state.count=state.count-1;return _virtual_index' },
        code: { actions: { click: 'state.count = state.count - 1;\n' } },
        id: 'builder-ba996ea9f0084bdd8aae0647b86ce52a',
        meta: {
          eventActions: {
            click: [
              {
                '@type': '@builder.io/core:Action',
                action: '@builder.io:customCode',
                options: { code: 'state.count = state.count - 1' },
              },
            ],
          },
        },
        component: { name: 'CustomButton', options: {} },
        children: [
          {
            '@type': '@builder.io/sdk:Element',
            '@version': 2,
            id: 'builder-f57f617953874530a5e0be5e1afe207c',
            component: { name: 'Text', options: { text: 'decrement' } },
            responsiveStyles: {
              large: {
                display: 'flex',
                flexDirection: 'column',
                position: 'relative',
                flexShrink: '0',
                boxSizing: 'border-box',
                marginTop: '0px',
                lineHeight: 'normal',
                height: 'auto',
                fontSize: '24px',
              },
            },
          },
        ],
        responsiveStyles: {
          large: {
            display: 'flex',
            flexDirection: 'column',
            position: 'relative',
            flexShrink: '0',
            boxSizing: 'border-box',
            marginTop: '20px',
            paddingTop: '20px',
            paddingBottom: '20px',
            paddingLeft: '40px',
            paddingRight: '40px',
          },
        },
      },
      {
        '@type': '@builder.io/sdk:Element',
        '@version': 2,
        id: 'builder-b06ca0ce4b4142f6a21fffa9dcc81c68',
        component: { name: 'CustomButton', options: {} },
        children: [
          {
            '@type': '@builder.io/sdk:Element',
            '@version': 2,
            id: 'builder-30cdd826e76f427893b59920dee23f49',
            component: { name: 'Text', options: { text: 'RED BUTTON' } },
            responsiveStyles: {
              large: {
                display: 'flex',
                flexDirection: 'column',
                position: 'relative',
                flexShrink: '0',
                boxSizing: 'border-box',
                marginTop: '0px',
                lineHeight: 'normal',
                height: 'auto',
                color: 'rgba(255, 255, 255, 1)',
              },
            },
          },
        ],
        responsiveStyles: {
          large: {
            display: 'flex',
            flexDirection: 'column',
            position: 'relative',
            flexShrink: '0',
            boxSizing: 'border-box',
            marginTop: '20px',
            backgroundColor: 'red',
          },
        },
      },
      {
        '@type': '@builder.io/sdk:Element',
        '@version': 2,
        id: 'builder-63252f94da4046609a58019f8b0e2aed',
        meta: { previousId: 'builder-b06ca0ce4b4142f6a21fffa9dcc81c68' },
        component: { name: 'CustomButton', options: {} },
        children: [
          {
            '@type': '@builder.io/sdk:Element',
            '@version': 2,
            id: 'builder-3d8fe83e6000473b8d1d49493fc205ac',
            meta: { previousId: 'builder-30cdd826e76f427893b59920dee23f49' },
            component: { name: 'Text', options: { text: 'BLUE BUTTON' } },
            responsiveStyles: {
              large: {
                display: 'flex',
                flexDirection: 'column',
                position: 'relative',
                flexShrink: '0',
                boxSizing: 'border-box',
                marginTop: '0px',
                lineHeight: 'normal',
                height: 'auto',
                color: 'rgba(255, 255, 255, 1)',
              },
            },
          },
        ],
        responsiveStyles: {
          large: {
            display: 'flex',
            flexDirection: 'column',
            position: 'relative',
            flexShrink: '0',
            boxSizing: 'border-box',
            marginTop: '20px',
            backgroundColor: 'blue',
          },
        },
      },
      {
        '@type': '@builder.io/sdk:Element',
        '@version': 2,
        id: 'builder-8ed04aee57504296a58f421f6d144090',
        meta: { previousId: 'builder-b06ca0ce4b4142f6a21fffa9dcc81c68' },
        component: { name: 'CustomButton', options: {} },
        children: [
          {
            '@type': '@builder.io/sdk:Element',
            '@version': 2,
            id: 'builder-696431335b814849b18481f7100ffa33',
            meta: { previousId: 'builder-30cdd826e76f427893b59920dee23f49' },
            component: { name: 'Text', options: { text: 'GREEN BUTTON' } },
            responsiveStyles: {
              large: {
                display: 'flex',
                flexDirection: 'column',
                position: 'relative',
                flexShrink: '0',
                boxSizing: 'border-box',
                marginTop: '0px',
                lineHeight: 'normal',
                height: 'auto',
                color: 'rgba(255, 255, 255, 1)',
              },
            },
          },
        ],
        responsiveStyles: {
          large: {
            display: 'flex',
            flexDirection: 'column',
            position: 'relative',
            flexShrink: '0',
            boxSizing: 'border-box',
            marginTop: '20px',
            backgroundColor: 'green',
          },
        },
      },
      {
        '@type': '@builder.io/sdk:Element',
        '@version': 2,
        id: 'builder-d0a79e1e11744b27a21fbd28198ed60b',
        meta: { previousId: 'builder-b06ca0ce4b4142f6a21fffa9dcc81c68' },
        component: { name: 'CustomButton', options: {} },
        children: [
          {
            '@type': '@builder.io/sdk:Element',
            '@version': 2,
            id: 'builder-a8f94ed4d54c43c79cfeb187e34aa950',
            meta: { previousId: 'builder-30cdd826e76f427893b59920dee23f49' },
            component: { name: 'Text', options: { text: 'YELLOW BUTTON' } },
            responsiveStyles: {
              large: {
                display: 'flex',
                flexDirection: 'column',
                position: 'relative',
                flexShrink: '0',
                boxSizing: 'border-box',
                marginTop: '0px',
                lineHeight: 'normal',
                height: 'auto',
                color: 'black',
              },
            },
          },
        ],
        responsiveStyles: {
          large: {
            display: 'flex',
            flexDirection: 'column',
            position: 'relative',
            flexShrink: '0',
            boxSizing: 'border-box',
            marginTop: '20px',
            backgroundColor: 'yellow',
          },
        },
      },
      {
        '@type': '@builder.io/sdk:Element',
        '@version': 2,
        id: 'builder-83f6e16034594000923c37f1cebd24c0',
        meta: { previousId: 'builder-341c0f3ab2024f009df1edd609a9c906' },
        component: { name: 'Text', options: { text: '<b>CUSTOM CARDS (noWrap = true)</b>' } },
        responsiveStyles: {
          large: {
            display: 'flex',
            flexDirection: 'column',
            position: 'relative',
            flexShrink: '0',
            boxSizing: 'border-box',
            marginTop: '20px',
            lineHeight: 'normal',
            height: 'auto',
            fontSize: '40px',
          },
        },
      },
      {
        '@type': '@builder.io/sdk:Element',
        '@version': 2,
        id: 'builder-d0e202719bba4f7d8bc5cb727732d406',
        component: { name: 'CustomCard', options: {} },
        children: [
          {
            '@type': '@builder.io/sdk:Element',
            '@version': 2,
            id: 'builder-105d0d6f191b4ebdacce3a5596a52bf0',
            component: { name: 'CustomCardTitle', options: {} },
            children: [
              {
                '@type': '@builder.io/sdk:Element',
                '@version': 2,
                id: 'builder-90abcb5a12ba4064937254b70229bf03',
                component: { name: 'Text', options: { text: 'Card title 1' } },
                responsiveStyles: {
                  large: {
                    display: 'flex',
                    flexDirection: 'column',
                    position: 'relative',
                    flexShrink: '0',
                    boxSizing: 'border-box',
                    marginTop: '20px',
                    lineHeight: 'normal',
                    height: 'auto',
                  },
                },
              },
            ],
            responsiveStyles: {
              large: {
                display: 'flex',
                flexDirection: 'column',
                position: 'relative',
                flexShrink: '0',
                boxSizing: 'border-box',
                marginTop: '20px',
              },
            },
          },
          {
            '@type': '@builder.io/sdk:Element',
            '@version': 2,
            id: 'builder-28b56d4ebd43460c8e938f5c2b3ad56d',
            component: { name: 'CustomCardContent', options: {} },
            children: [
              {
                '@type': '@builder.io/sdk:Element',
                '@version': 2,
                id: 'builder-648d02d2ff4e45f2a152c49aad6961e2',
                meta: { previousId: 'builder-90abcb5a12ba4064937254b70229bf03' },
                component: {
                  name: 'Text',
                  options: {
                    text: '<span style="font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; text-align: justify; background-color: rgb(255, 255, 255);">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ornare libero id vestibulum convallis. In hac habitasse platea dictumst. Curabitur euismod justo enim, vel rutrum nisi blandit sagittis. Sed in justo nisl. Morbi non nisi a arcu hendrerit sollicitudin. Phasellus eleifend ac sem ac consectetur. Mauris venenatis tortor at condimentum pulvinar. Morbi et accumsan risus. Duis vitae nisl hendrerit, sagittis leo ut, laoreet libero. In hac habitasse platea dictumst. Fusce id vulputate ligula, in facilisis dolor. Fusce eu erat accumsan, faucibus enim et, posuere sem. Suspendisse varius eleifend pretium. Morbi eleifend consectetur ipsum ut sollicitudin. Vivamus eget urna ut nisl tristique ultricies. In consectetur tortor at lectus dignissim faucibus.</span>',
                  },
                },
                responsiveStyles: {
                  large: {
                    display: 'flex',
                    flexDirection: 'column',
                    position: 'relative',
                    flexShrink: '0',
                    boxSizing: 'border-box',
                    marginTop: '20px',
                    lineHeight: 'normal',
                    height: 'auto',
                  },
                },
              },
            ],
            responsiveStyles: {
              large: {
                display: 'flex',
                flexDirection: 'column',
                position: 'relative',
                flexShrink: '0',
                boxSizing: 'border-box',
                marginTop: '20px',
              },
            },
          },
          {
            '@type': '@builder.io/sdk:Element',
            '@version': 2,
            id: 'builder-58f033eeba614a868ffc60bb2d68a62a',
            component: { name: 'CustomCardFooter', options: {} },
            children: [
              {
                '@type': '@builder.io/sdk:Element',
                '@version': 2,
                id: 'builder-91f8a367b3f54957be48bb1c7ca1ed5b',
                meta: { previousId: 'builder-90abcb5a12ba4064937254b70229bf03' },
                component: { name: 'Text', options: { text: 'Card footer' } },
                responsiveStyles: {
                  large: {
                    display: 'flex',
                    flexDirection: 'column',
                    position: 'relative',
                    flexShrink: '0',
                    boxSizing: 'border-box',
                    marginTop: '20px',
                    lineHeight: 'normal',
                    height: 'auto',
                  },
                },
              },
            ],
            responsiveStyles: {
              large: {
                display: 'flex',
                flexDirection: 'column',
                position: 'relative',
                flexShrink: '0',
                boxSizing: 'border-box',
                marginTop: '0px',
              },
            },
          },
        ],
        responsiveStyles: {
          large: {
            display: 'flex',
            flexDirection: 'column',
            position: 'relative',
            flexShrink: '0',
            boxSizing: 'border-box',
            marginTop: '20px',
            backgroundColor: 'rgba(255, 254, 234, 1)',
          },
        },
      },
      {
        '@type': '@builder.io/sdk:Element',
        '@version': 2,
        id: 'builder-1c47c9aa27fc4a4ca89693ecf320ee6c',
        meta: { previousId: 'builder-d0e202719bba4f7d8bc5cb727732d406' },
        component: { name: 'CustomCard', options: {} },
        children: [
          {
            '@type': '@builder.io/sdk:Element',
            '@version': 2,
            id: 'builder-40b5de4750c844a3852bf69335a0be6a',
            meta: { previousId: 'builder-105d0d6f191b4ebdacce3a5596a52bf0' },
            component: { name: 'CustomCardTitle', options: {} },
            children: [
              {
                '@type': '@builder.io/sdk:Element',
                '@version': 2,
                id: 'builder-b3306a0cb1c94a5cb5064ffb0cb4bda7',
                meta: { previousId: 'builder-90abcb5a12ba4064937254b70229bf03' },
                component: { name: 'Text', options: { text: 'Card title 2' } },
                responsiveStyles: {
                  large: {
                    display: 'flex',
                    flexDirection: 'column',
                    position: 'relative',
                    flexShrink: '0',
                    boxSizing: 'border-box',
                    marginTop: '20px',
                    lineHeight: 'normal',
                    height: 'auto',
                  },
                },
              },
            ],
            responsiveStyles: {
              large: {
                display: 'flex',
                flexDirection: 'column',
                position: 'relative',
                flexShrink: '0',
                boxSizing: 'border-box',
                marginTop: '20px',
              },
            },
          },
          {
            '@type': '@builder.io/sdk:Element',
            '@version': 2,
            id: 'builder-9ab46bb50ae846ebaad465db1dfa1879',
            meta: { previousId: 'builder-28b56d4ebd43460c8e938f5c2b3ad56d' },
            component: { name: 'CustomCardContent', options: {} },
            children: [
              {
                '@type': '@builder.io/sdk:Element',
                '@version': 2,
                id: 'builder-3f8e8ab087ac4f85a4d9a86e53804de9',
                meta: { previousId: 'builder-648d02d2ff4e45f2a152c49aad6961e2' },
                component: {
                  name: 'Text',
                  options: {
                    text: '<span style="font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; text-align: justify; background-color: rgb(255, 255, 255);">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ornare libero id vestibulum convallis. In hac habitasse platea dictumst. Curabitur euismod justo enim, vel rutrum nisi blandit sagittis. Sed in justo nisl. Morbi non nisi a arcu hendrerit sollicitudin. Phasellus eleifend ac sem ac consectetur. Mauris venenatis tortor at condimentum pulvinar. Morbi et accumsan risus. Duis vitae nisl hendrerit, sagittis leo ut, laoreet libero. In hac habitasse platea dictumst. Fusce id vulputate ligula, in facilisis dolor. Fusce eu erat accumsan, faucibus enim et, posuere sem. Suspendisse varius eleifend pretium. Morbi eleifend consectetur ipsum ut sollicitudin. Vivamus eget urna ut nisl tristique ultricies. In consectetur tortor at lectus dignissim faucibus.</span>',
                  },
                },
                responsiveStyles: {
                  large: {
                    display: 'flex',
                    flexDirection: 'column',
                    position: 'relative',
                    flexShrink: '0',
                    boxSizing: 'border-box',
                    marginTop: '20px',
                    lineHeight: 'normal',
                    height: 'auto',
                  },
                },
              },
            ],
            responsiveStyles: {
              large: {
                display: 'flex',
                flexDirection: 'column',
                position: 'relative',
                flexShrink: '0',
                boxSizing: 'border-box',
                marginTop: '20px',
              },
            },
          },
          {
            '@type': '@builder.io/sdk:Element',
            '@version': 2,
            id: 'builder-6d95ec50a3b340bd830e4e974303c35e',
            meta: { previousId: 'builder-58f033eeba614a868ffc60bb2d68a62a' },
            component: { name: 'CustomCardFooter', options: {} },
            children: [
              {
                '@type': '@builder.io/sdk:Element',
                '@version': 2,
                id: 'builder-448d66c6074744e1bb25ed9ccb836cca',
                meta: { previousId: 'builder-91f8a367b3f54957be48bb1c7ca1ed5b' },
                component: { name: 'Text', options: { text: 'Card footer' } },
                responsiveStyles: {
                  large: {
                    display: 'flex',
                    flexDirection: 'column',
                    position: 'relative',
                    flexShrink: '0',
                    boxSizing: 'border-box',
                    marginTop: '20px',
                    lineHeight: 'normal',
                    height: 'auto',
                  },
                },
              },
            ],
            responsiveStyles: {
              large: {
                display: 'flex',
                flexDirection: 'column',
                position: 'relative',
                flexShrink: '0',
                boxSizing: 'border-box',
                marginTop: '0px',
              },
            },
          },
        ],
        responsiveStyles: {
          large: {
            display: 'flex',
            flexDirection: 'column',
            position: 'relative',
            flexShrink: '0',
            boxSizing: 'border-box',
            marginTop: '20px',
            backgroundColor: 'rgba(255, 240, 223, 1)',
            borderRadius: '50px',
          },
        },
      },
      {
        '@type': '@builder.io/sdk:Element',
        '@version': 2,
        id: 'builder-0e17b2cb2f8d46bfa14deb931d554c65',
        meta: { previousId: 'builder-d0e202719bba4f7d8bc5cb727732d406' },
        component: { name: 'CustomCard', options: {} },
        children: [
          {
            '@type': '@builder.io/sdk:Element',
            '@version': 2,
            id: 'builder-3afa99d3dd97432d88e2802782a10259',
            meta: { previousId: 'builder-105d0d6f191b4ebdacce3a5596a52bf0' },
            component: { name: 'CustomCardTitle', options: {} },
            children: [
              {
                '@type': '@builder.io/sdk:Element',
                '@version': 2,
                id: 'builder-141ff7b53809405bbdf603865e9a765f',
                meta: { previousId: 'builder-90abcb5a12ba4064937254b70229bf03' },
                component: { name: 'Text', options: { text: 'Card title 3' } },
                responsiveStyles: {
                  large: {
                    display: 'flex',
                    flexDirection: 'column',
                    position: 'relative',
                    flexShrink: '0',
                    boxSizing: 'border-box',
                    marginTop: '20px',
                    lineHeight: 'normal',
                    height: 'auto',
                  },
                },
              },
            ],
            responsiveStyles: {
              large: {
                display: 'flex',
                flexDirection: 'column',
                position: 'relative',
                flexShrink: '0',
                boxSizing: 'border-box',
                marginTop: '20px',
              },
            },
          },
          {
            '@type': '@builder.io/sdk:Element',
            '@version': 2,
            id: 'builder-b807e032e7974bff89f9ceccb5db3c56',
            meta: { previousId: 'builder-28b56d4ebd43460c8e938f5c2b3ad56d' },
            component: { name: 'CustomCardContent', options: {} },
            children: [
              {
                '@type': '@builder.io/sdk:Element',
                '@version': 2,
                id: 'builder-44480b52d04e4d269ff503fe2b337add',
                meta: { previousId: 'builder-648d02d2ff4e45f2a152c49aad6961e2' },
                component: {
                  name: 'Text',
                  options: {
                    text: '<span style="font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; text-align: justify; background-color: rgb(255, 255, 255);">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ornare libero id vestibulum convallis. In hac habitasse platea dictumst. Curabitur euismod justo enim, vel rutrum nisi blandit sagittis. Sed in justo nisl. Morbi non nisi a arcu hendrerit sollicitudin. Phasellus eleifend ac sem ac consectetur. Mauris venenatis tortor at condimentum pulvinar. Morbi et accumsan risus. Duis vitae nisl hendrerit, sagittis leo ut, laoreet libero. In hac habitasse platea dictumst. Fusce id vulputate ligula, in facilisis dolor. Fusce eu erat accumsan, faucibus enim et, posuere sem. Suspendisse varius eleifend pretium. Morbi eleifend consectetur ipsum ut sollicitudin. Vivamus eget urna ut nisl tristique ultricies. In consectetur tortor at lectus dignissim faucibus.</span>',
                  },
                },
                responsiveStyles: {
                  large: {
                    display: 'flex',
                    flexDirection: 'column',
                    position: 'relative',
                    flexShrink: '0',
                    boxSizing: 'border-box',
                    marginTop: '20px',
                    lineHeight: 'normal',
                    height: 'auto',
                  },
                },
              },
            ],
            responsiveStyles: {
              large: {
                display: 'flex',
                flexDirection: 'column',
                position: 'relative',
                flexShrink: '0',
                boxSizing: 'border-box',
                marginTop: '20px',
              },
            },
          },
          {
            '@type': '@builder.io/sdk:Element',
            '@version': 2,
            id: 'builder-9021b4d510414f7e9dda7528d6074373',
            meta: { previousId: 'builder-58f033eeba614a868ffc60bb2d68a62a' },
            component: { name: 'CustomCardFooter', options: {} },
            children: [
              {
                '@type': '@builder.io/sdk:Element',
                '@version': 2,
                id: 'builder-7507bd9c40204410a467a654ba24bd62',
                meta: { previousId: 'builder-91f8a367b3f54957be48bb1c7ca1ed5b' },
                component: { name: 'Text', options: { text: 'Card footer' } },
                responsiveStyles: {
                  large: {
                    display: 'flex',
                    flexDirection: 'column',
                    position: 'relative',
                    flexShrink: '0',
                    boxSizing: 'border-box',
                    marginTop: '20px',
                    lineHeight: 'normal',
                    height: 'auto',
                  },
                },
              },
            ],
            responsiveStyles: {
              large: {
                display: 'flex',
                flexDirection: 'column',
                position: 'relative',
                flexShrink: '0',
                boxSizing: 'border-box',
                marginTop: '0px',
              },
            },
          },
        ],
        responsiveStyles: {
          large: {
            display: 'flex',
            flexDirection: 'column',
            position: 'relative',
            flexShrink: '0',
            boxSizing: 'border-box',
            marginTop: '20px',
            backgroundColor: 'rgba(252, 241, 255, 1)',
            borderRadius: '20px',
          },
        },
      },
    ],
  },
  metrics: {
    clicks: 0,
    impressions: 0,
  },
  variations: {},
  lastUpdated: 1729922960920,
  testRatio: 1,
  createdBy: 'RuGeCLr9ryVt1xRazFYc72uWwIK2',
  lastUpdatedBy: 'RuGeCLr9ryVt1xRazFYc72uWwIK2',
  folders: [],
};
