export const INPUT_DEFAULT_VALUE = {
  data: {
    title: 'default-input-value',
    themeId: false,
    newField3: 'testing',
    inputs: [
      {
        '@type': '@builder.io/core:Field',
        name: 'x',
        type: 'text',
        defaultValue: 'init value',
        required: false,
        subFields: [],
        helperText: '',
        autoFocus: false,
        simpleTextOnly: false,
        disallowRemove: false,
        broadcast: false,
        bubble: false,
        hideFromUI: false,
        hideFromFieldsEditor: false,
        showTemplatePicker: true,
        permissionsRequiredToEdit: '',
        advanced: false,
        copyOnAdd: true,
        onChange: '',
        showIf: '',
        mandatory: false,
        hidden: false,
        noPhotoPicker: false,
        model: '',
        supportsAiGeneration: false,
        defaultCollapsed: false,
      },
    ],
    blocks: [
      {
        '@type': '@builder.io/sdk:Element',
        '@version': 2,
        bindings: {
          'component.options.text': 'var _virtual_index=state.x;return _virtual_index',
        },
        code: { bindings: { 'component.options.text': 'state.x' } },
        id: 'builder-f11cc1b21398436184379b7ac16187fb',
        component: { name: 'Text', options: { text: 'Enter some text...' } },
        responsiveStyles: {
          large: {
            display: 'flex',
            flexDirection: 'column',
            position: 'relative',
            flexShrink: '0',
            boxSizing: 'border-box',
            marginTop: '20px',
            lineHeight: 'normal',
            height: 'auto',
          },
        },
      },
    ],
  },
};
