export const CONTENT = {
  lastUpdatedBy: 'nwUXoMIBfvZJtUfPGEvR14NW3OJ2',
  folders: [],
  data: {
    blocks: [
      {
        '@type': '@builder.io/sdk:Element',
        '@version': 2,
        id: 'builder-57a957f9c48341b8868ecffb8516152f',
        component: {
          name: 'Symbol',
          options: {
            dataOnly: false,
            inheritState: true,
            renderToLiquid: false,
            symbol: {
              model: 'symbol',
              entry: '43c02d9ee3154951959be8bf85f3cb90',
              content: {
                lastUpdatedBy: 'nwUXoMIBfvZJtUfPGEvR14NW3OJ2',
                folders: [],
                data: {
                  blocks: [
                    {
                      '@type': '@builder.io/sdk:Element',
                      '@version': 2,
                      id: 'builder-da99c9b381c94872b104752ef82b296b',
                      children: [
                        {
                          '@type': '@builder.io/sdk:Element',
                          '@version': 2,
                          id: 'builder-568c12de47604215a796c38f30d21c90',
                          component: { name: 'Text', options: { text: '<p>Card symbol</p>' } },
                          responsiveStyles: {
                            large: {
                              display: 'flex',
                              flexDirection: 'column',
                              position: 'relative',
                              flexShrink: '0',
                              boxSizing: 'border-box',
                              marginTop: '20px',
                              lineHeight: 'normal',
                              height: 'auto',
                            },
                          },
                        },
                        {
                          '@type': '@builder.io/sdk:Element',
                          '@version': 2,
                          id: 'builder-69fe1768b0264789a0395cbd9e6ed678',
                          component: {
                            name: 'Core:Button',
                            options: { text: 'Click me!', openLinkInNewTab: false },
                          },
                          responsiveStyles: {
                            large: {
                              display: 'flex',
                              flexDirection: 'column',
                              position: 'relative',
                              flexShrink: '0',
                              boxSizing: 'border-box',
                              marginTop: '20px',
                              appearance: 'none',
                              paddingTop: '15px',
                              paddingBottom: '15px',
                              paddingLeft: '25px',
                              paddingRight: '25px',
                              backgroundColor: 'black',
                              color: 'white',
                              borderRadius: '4px',
                              textAlign: 'center',
                              cursor: 'pointer',
                            },
                          },
                        },
                        {
                          '@type': '@builder.io/sdk:Element',
                          '@version': 2,
                          id: 'builder-1256434ce42d4573944378dfaf40f727',
                          component: {
                            name: 'Symbol',
                            options: {
                              dataOnly: false,
                              inheritState: true,
                              renderToLiquid: false,
                              symbol: {
                                model: 'symbol',
                                entry: 'b5da5128f0e340cabe2af797887325fc',
                                content: {
                                  lastUpdatedBy: 'nwUXoMIBfvZJtUfPGEvR14NW3OJ2',
                                  folders: [],
                                  data: {
                                    blocks: [
                                      {
                                        '@type': '@builder.io/sdk:Element',
                                        '@version': 2,
                                        id: 'builder-c45d3e16b4d642bcb500de8d9908bb21',
                                        children: [
                                          {
                                            '@type': '@builder.io/sdk:Element',
                                            '@version': 2,
                                            id: 'builder-915c97cf68194d6a9d500a2c01ab48ff',
                                            component: {
                                              name: 'Text',
                                              options: { text: '<p>Child Symbol</p>' },
                                            },
                                            responsiveStyles: {
                                              large: {
                                                display: 'flex',
                                                flexDirection: 'column',
                                                position: 'relative',
                                                flexShrink: '0',
                                                boxSizing: 'border-box',
                                                marginTop: '20px',
                                                lineHeight: 'normal',
                                                height: 'auto',
                                              },
                                            },
                                          },
                                        ],
                                        responsiveStyles: {
                                          large: {
                                            display: 'flex',
                                            flexDirection: 'column',
                                            position: 'relative',
                                            flexShrink: '0',
                                            boxSizing: 'border-box',
                                            marginTop: '20px',
                                            height: 'auto',
                                            paddingBottom: '30px',
                                          },
                                        },
                                      },
                                      {
                                        '@type': '@builder.io/sdk:Element',
                                        '@version': 2,
                                        id: 'builder-524ac63d0be54ca79d0e54cef96ab4e1',
                                        component: {
                                          name: 'Core:Button',
                                          options: { text: 'Click me!', openLinkInNewTab: false },
                                        },
                                        responsiveStyles: {
                                          large: {
                                            display: 'flex',
                                            flexDirection: 'column',
                                            position: 'relative',
                                            flexShrink: '0',
                                            boxSizing: 'border-box',
                                            marginTop: '20px',
                                            appearance: 'none',
                                            paddingTop: '15px',
                                            paddingBottom: '15px',
                                            paddingLeft: '25px',
                                            paddingRight: '25px',
                                            backgroundColor: 'black',
                                            color: 'white',
                                            borderRadius: '4px',
                                            textAlign: 'center',
                                            cursor: 'pointer',
                                          },
                                        },
                                      },
                                    ],
                                  },
                                  modelId: '0ae955fb4ece4430949be04b3003d8fe',
                                  query: [],
                                  published: 'published',
                                  ownerId: 'c7d228a41c874fcf849329fdfdd74bb1',
                                  priority: -91.5,
                                  firstPublished: 1692863026552,
                                  testRatio: 1,
                                  lastUpdated: 1692863026579,
                                  createdDate: 1692862915453,
                                  createdBy: 'nwUXoMIBfvZJtUfPGEvR14NW3OJ2',
                                  meta: {
                                    kind: 'component',
                                    lastPreviewUrl:
                                      'https://preview.builder.codes/?model=symbol&apiKey=c7d228a41c874fcf849329fdfdd74bb1&builder.space=c7d228a41c874fcf849329fdfdd74bb1&builder.cachebust=true&builder.preview=symbol&builder.noCache=true&__builder_editing__=true&builder.overrides.symbol=b5da5128f0e340cabe2af797887325fc&builder.overrides.b5da5128f0e340cabe2af797887325fc=b5da5128f0e340cabe2af797887325fc',
                                    hasLinks: false,
                                  },
                                  variations: {},
                                  '@version': 4,
                                  name: 'button-symbol',
                                  id: 'b5da5128f0e340cabe2af797887325fc',
                                  metrics: {
                                    clicks: 0,
                                    impressions: 0,
                                  },
                                  lastUpdateBy: null,
                                },
                                data: {},
                                ownerId: 'c7d228a41c874fcf849329fdfdd74bb1',
                                global: false,
                              },
                            },
                          },
                          responsiveStyles: {
                            large: {
                              display: 'flex',
                              flexDirection: 'column',
                              position: 'relative',
                              flexShrink: '0',
                              boxSizing: 'border-box',
                              marginTop: '20px',
                            },
                          },
                        },
                      ],
                      responsiveStyles: {
                        large: {
                          display: 'flex',
                          flexDirection: 'column',
                          position: 'relative',
                          flexShrink: '0',
                          boxSizing: 'border-box',
                          marginTop: '20px',
                          height: 'auto',
                          paddingBottom: '30px',
                        },
                      },
                    },
                  ],
                },
                modelId: '0ae955fb4ece4430949be04b3003d8fe',
                query: [],
                published: 'published',
                ownerId: 'c7d228a41c874fcf849329fdfdd74bb1',
                priority: -96.5,
                firstPublished: 1692863115395,
                testRatio: 1,
                lastUpdated: 1692863115411,
                createdDate: 1692863043278,
                createdBy: 'nwUXoMIBfvZJtUfPGEvR14NW3OJ2',
                meta: {
                  kind: 'component',
                  lastPreviewUrl:
                    'https://preview.builder.codes?model=symbol&previewing=true&apiKey=c7d228a41c874fcf849329fdfdd74bb1&builder.space=c7d228a41c874fcf849329fdfdd74bb1&builder.cachebust=true&builder.preview=symbol&builder.noCache=true&__builder_editing__=true&builder.overrides.symbol=43c02d9ee3154951959be8bf85f3cb90&builder.overrides.43c02d9ee3154951959be8bf85f3cb90=43c02d9ee3154951959be8bf85f3cb90',
                  hasLinks: false,
                },
                variations: {},
                '@version': 4,
                name: 'card-symbol',
                id: '43c02d9ee3154951959be8bf85f3cb90',
                metrics: {
                  clicks: 0,
                  impressions: 0,
                },
                lastUpdateBy: null,
              },
              data: {},
              ownerId: 'c7d228a41c874fcf849329fdfdd74bb1',
              global: false,
            },
          },
        },
        responsiveStyles: {
          large: {
            display: 'flex',
            flexDirection: 'column',
            position: 'relative',
            flexShrink: '0',
            boxSizing: 'border-box',
            marginTop: '20px',
          },
        },
      },
    ],
    url: '/nested-symbols',
    state: {
      deviceSize: 'large',
      location: { pathname: '/nested-symbols', path: ['symbols'], query: {} },
    },
    themeId: false,
    title: 'main page',
  },
  modelId: '97c1ea6dd7004775a3220618f816dda7',
  query: [
    {
      '@type': '@builder.io/core:Query',
      property: 'urlPath',
      value: '/nested-symbols',
      operator: 'is',
    },
  ],
  published: 'published',
  ownerId: 'c7d228a41c874fcf849329fdfdd74bb1',
  priority: -101.5,
  firstPublished: 1692863255377,
  testRatio: 1,
  lastUpdated: 1692863255389,
  createdDate: 1692863140500,
  createdBy: 'nwUXoMIBfvZJtUfPGEvR14NW3OJ2',
  meta: {
    kind: 'page',
    lastPreviewUrl:
      'https://preview.builder.codes?model=page&previewing=true&apiKey=c7d228a41c874fcf849329fdfdd74bb1&builder.space=c7d228a41c874fcf849329fdfdd74bb1&builder.cachebust=true&builder.preview=page&builder.noCache=true&__builder_editing__=true&builder.overrides.page=4617a1ce8eda49788e97dd891bc1d8c3&builder.overrides.4617a1ce8eda49788e97dd891bc1d8c3=4617a1ce8eda49788e97dd891bc1d8c3&builder.overrides.page:/=4617a1ce8eda49788e97dd891bc1d8c3',
    hasLinks: false,
    symbolsUsed: {
      '43c02d9ee3154951959be8bf85f3cb90': true,
      b5da5128f0e340cabe2af797887325fc: true,
    },
  },
  variations: {},
  '@version': 4,
  name: 'main page',
  id: '4617a1ce8eda49788e97dd891bc1d8c3',
  metrics: {
    clicks: 0,
    impressions: 0,
  },
  lastUpdateBy: null,
};
