export const CONTENT = {
  data: {
    title: 'inline-personalization',
    blocks: [
      {
        '@type': '@builder.io/sdk:Element',
        '@version': 2,
        id: 'builder-945494d83b6b4142b6b663130cee2af0',
        component: {
          name: 'Image',
          options: {
            image:
              'https://cdn.builder.io/api/v1/image/assets%2F802a1eea7c44430aa23d4b9c708d07ad%2Fc27867fc7fa44b949ce9881e92276e26?width=1880',
            backgroundSize: 'cover',
            backgroundPosition: 'center',
            lazy: false,
            aspectRatio: 0.285,
            sizes: '(max-width: 638px) 94vw, (max-width: 998px) 96vw, 135vw',
            height: 1253,
            width: 1880,
          },
        },
        children: [
          {
            '@type': '@builder.io/sdk:Element',
            '@version': 2,
            id: 'builder-833e9f232cd1441ea89d7da77a033e4a',
            children: [
              {
                '@type': '@builder.io/sdk:Element',
                '@version': 2,
                id: 'builder-572b33cad7324e1c81bd77eddf8fc995',
                component: {
                  name: 'Text',
                  options: {
                    text: '<p>Non personalized</p>',
                  },
                },
                responsiveStyles: {
                  large: {
                    display: 'flex',
                    flexDirection: 'column',
                    alignItems: 'stretch',
                    position: 'relative',
                    flexShrink: '0',
                    boxSizing: 'border-box',
                    marginLeft: '20px',
                    lineHeight: 'normal',
                    height: 'auto',
                    textAlign: 'center',
                    fontSize: '72px',
                    color: 'rgba(255, 255, 255, 1)',
                    textShadow: '1px 3px 3px rgba(0, 0, 0, 1)',
                  },
                  small: {
                    marginLeft: '0px',
                    fontSize: '52px',
                  },
                },
              },
              {
                '@type': '@builder.io/sdk:Element',
                '@version': 2,
                id: 'builder-08661ce70efd4070820564b3b80b18a6',
                component: {
                  name: 'Text',
                  options: {
                    text: '<p>Find Valentine Reads Here!</p>',
                  },
                },
                responsiveStyles: {
                  large: {
                    display: 'flex',
                    flexDirection: 'column',
                    alignItems: 'stretch',
                    position: 'relative',
                    flexShrink: '0',
                    boxSizing: 'border-box',
                    marginLeft: 'auto',
                    lineHeight: 'normal',
                    height: 'auto',
                    textAlign: 'center',
                    width: '20%',
                    marginRight: 'auto',
                    color: 'rgba(255, 255, 255, 1)',
                    textShadow: '1.5px 1px 3px rgba(0, 0, 0, 1)',
                  },
                  medium: {
                    width: '40%',
                  },
                  small: {
                    width: '70%',
                  },
                },
              },
              {
                '@type': '@builder.io/sdk:Element',
                '@version': 2,
                id: 'builder-ca483a95de774dd0a17a96b28d06648f',
                component: {
                  name: 'Core:Button',
                  options: {
                    text: 'ROMANCE NOVELS',
                  },
                },
                responsiveStyles: {
                  large: {
                    display: 'flex',
                    flexDirection: 'column',
                    alignItems: 'stretch',
                    position: 'relative',
                    flexShrink: '0',
                    boxSizing: 'border-box',
                    marginTop: '20px',
                    appearance: 'none',
                    paddingTop: '15px',
                    paddingBottom: '15px',
                    paddingLeft: '25px',
                    paddingRight: '25px',
                    backgroundColor: 'rgba(172, 38, 38, 1)',
                    color: 'white',
                    borderRadius: '24px',
                    textAlign: 'center',
                    cursor: 'pointer',
                    width: 'auto',
                    alignSelf: 'center',
                    fontWeight: '600',
                  },
                },
              },
            ],
            responsiveStyles: {
              large: {
                display: 'flex',
                flexDirection: 'column',
                alignItems: 'stretch',
                position: 'relative',
                flexShrink: '0',
                boxSizing: 'border-box',
                marginTop: 'auto',
                height: 'auto',
                paddingBottom: '30px',
                marginBottom: 'auto',
              },
            },
          },
        ],
        responsiveStyles: {
          large: {
            display: 'flex',
            flexDirection: 'column',
            alignItems: 'stretch',
            position: 'relative',
            flexShrink: '0',
            boxSizing: 'border-box',
            minHeight: '500px',
            minWidth: '20px',
            overflow: 'hidden',
            width: '100%',
          },
        },
      },
      {
        '@type': '@builder.io/sdk:Element',
        '@version': 2,
        id: 'builder-d6573a86bdf84c0e80c971e5ff0e2a12',
        component: {
          name: 'PersonalizationContainer',
          options: {
            variants: [
              {
                blocks: [
                  {
                    '@type': '@builder.io/sdk:Element',
                    '@version': 2,
                    id: 'builder-abdfa94a2ea4491583b3ecc8568c55b3',
                    component: {
                      name: 'Image',
                      options: {
                        image:
                          'https://cdn.builder.io/api/v1/image/assets%2F802a1eea7c44430aa23d4b9c708d07ad%2Fc27867fc7fa44b949ce9881e92276e26?width=1880',
                        backgroundSize: 'cover',
                        backgroundPosition: 'center',
                        lazy: false,
                        aspectRatio: 0.285,
                        sizes: '(max-width: 638px) 94vw, (max-width: 998px) 96vw, 135vw',
                        height: 1253,
                        width: 1880,
                      },
                    },
                    children: [
                      {
                        '@type': '@builder.io/sdk:Element',
                        '@version': 2,
                        id: 'builder-56222a5189f64fac842cfc4b18bf4ccd',
                        children: [
                          {
                            '@type': '@builder.io/sdk:Element',
                            '@version': 2,
                            id: 'builder-c91ab8a94cc64474aa068f97262da54c',
                            component: {
                              name: 'Text',
                              options: {
                                text: '<p>Experiment A</p>',
                              },
                            },
                            responsiveStyles: {
                              large: {
                                display: 'flex',
                                flexDirection: 'column',
                                alignItems: 'stretch',
                                position: 'relative',
                                flexShrink: '0',
                                boxSizing: 'border-box',
                                marginLeft: '20px',
                                lineHeight: 'normal',
                                height: 'auto',
                                textAlign: 'center',
                                fontSize: '72px',
                                color: 'rgba(255, 255, 255, 1)',
                                textShadow: '1px 3px 3px rgba(0, 0, 0, 1)',
                              },
                              small: {
                                marginLeft: '0px',
                                fontSize: '52px',
                              },
                            },
                          },
                          {
                            '@type': '@builder.io/sdk:Element',
                            '@version': 2,
                            id: 'builder-febb031369d14a3a8da5521f4a40c953',
                            component: {
                              name: 'Text',
                              options: {
                                text: '<p>Find Valentine Reads Here!</p>',
                              },
                            },
                            responsiveStyles: {
                              large: {
                                display: 'flex',
                                flexDirection: 'column',
                                alignItems: 'stretch',
                                position: 'relative',
                                flexShrink: '0',
                                boxSizing: 'border-box',
                                marginLeft: 'auto',
                                lineHeight: 'normal',
                                height: 'auto',
                                textAlign: 'center',
                                width: '20%',
                                marginRight: 'auto',
                                color: 'rgba(255, 255, 255, 1)',
                                textShadow: '1.5px 1px 3px rgba(0, 0, 0, 1)',
                              },
                              medium: {
                                width: '40%',
                              },
                              small: {
                                width: '70%',
                              },
                            },
                          },
                          {
                            '@type': '@builder.io/sdk:Element',
                            '@version': 2,
                            id: 'builder-ed0ea595a83f46f7862754e9dd1ab66c',
                            component: {
                              name: 'Core:Button',
                              options: {
                                text: 'ROMANCE NOVELS',
                              },
                            },
                            responsiveStyles: {
                              large: {
                                display: 'flex',
                                flexDirection: 'column',
                                alignItems: 'stretch',
                                position: 'relative',
                                flexShrink: '0',
                                boxSizing: 'border-box',
                                marginTop: '20px',
                                appearance: 'none',
                                paddingTop: '15px',
                                paddingBottom: '15px',
                                paddingLeft: '25px',
                                paddingRight: '25px',
                                backgroundColor: 'rgba(172, 38, 38, 1)',
                                color: 'white',
                                borderRadius: '24px',
                                textAlign: 'center',
                                cursor: 'pointer',
                                width: 'auto',
                                alignSelf: 'center',
                                fontWeight: '600',
                              },
                            },
                          },
                        ],
                        responsiveStyles: {
                          large: {
                            display: 'flex',
                            flexDirection: 'column',
                            alignItems: 'stretch',
                            position: 'relative',
                            flexShrink: '0',
                            boxSizing: 'border-box',
                            marginTop: 'auto',
                            height: 'auto',
                            paddingBottom: '30px',
                            marginBottom: 'auto',
                          },
                        },
                      },
                    ],
                    responsiveStyles: {
                      large: {
                        display: 'flex',
                        flexDirection: 'column',
                        alignItems: 'stretch',
                        position: 'relative',
                        flexShrink: '0',
                        boxSizing: 'border-box',
                        minHeight: '500px',
                        minWidth: '20px',
                        overflow: 'hidden',
                        width: '100%',
                      },
                    },
                  },
                ],
                query: [
                  {
                    '@type': '@builder.io/core:Query',
                    property: 'experiment',
                    operator: 'is',
                    value: ['A'],
                  },
                ],
                name: 'A',
              },
              {
                blocks: [
                  {
                    '@type': '@builder.io/sdk:Element',
                    '@version': 2,
                    id: 'builder-a2984dccd127479e973d8f9e5a75a64e',
                    component: {
                      name: 'Image',
                      options: {
                        image:
                          'https://cdn.builder.io/api/v1/image/assets%2F802a1eea7c44430aa23d4b9c708d07ad%2Fc27867fc7fa44b949ce9881e92276e26?width=1880',
                        backgroundSize: 'cover',
                        backgroundPosition: 'center',
                        lazy: false,
                        aspectRatio: 0.285,
                        sizes: '(max-width: 638px) 94vw, (max-width: 998px) 96vw, 135vw',
                        height: 1253,
                        width: 1880,
                      },
                    },
                    children: [
                      {
                        '@type': '@builder.io/sdk:Element',
                        '@version': 2,
                        id: 'builder-411c03d6bee547d4a47eebb7d9b8fd34',
                        children: [
                          {
                            '@type': '@builder.io/sdk:Element',
                            '@version': 2,
                            id: 'builder-32b40c7cfa064c4daaaf3b5113db44fc',
                            component: {
                              name: 'Text',
                              options: {
                                text: '<p>Experiment B</p>',
                              },
                            },
                            responsiveStyles: {
                              large: {
                                display: 'flex',
                                flexDirection: 'column',
                                alignItems: 'stretch',
                                position: 'relative',
                                flexShrink: '0',
                                boxSizing: 'border-box',
                                marginLeft: '20px',
                                lineHeight: 'normal',
                                height: 'auto',
                                textAlign: 'center',
                                fontSize: '72px',
                                color: 'rgba(255, 255, 255, 1)',
                                textShadow: '1px 3px 3px rgba(0, 0, 0, 1)',
                              },
                              small: {
                                marginLeft: '0px',
                                fontSize: '52px',
                              },
                            },
                          },
                          {
                            '@type': '@builder.io/sdk:Element',
                            '@version': 2,
                            id: 'builder-e3d48e5929154338a4c538a0e8a34114',
                            component: {
                              name: 'Text',
                              options: {
                                text: '<p>Find Valentine Reads Here!</p>',
                              },
                            },
                            responsiveStyles: {
                              large: {
                                display: 'flex',
                                flexDirection: 'column',
                                alignItems: 'stretch',
                                position: 'relative',
                                flexShrink: '0',
                                boxSizing: 'border-box',
                                marginLeft: 'auto',
                                lineHeight: 'normal',
                                height: 'auto',
                                textAlign: 'center',
                                width: '20%',
                                marginRight: 'auto',
                                color: 'rgba(255, 255, 255, 1)',
                                textShadow: '1.5px 1px 3px rgba(0, 0, 0, 1)',
                              },
                              medium: {
                                width: '40%',
                              },
                              small: {
                                width: '70%',
                              },
                            },
                          },
                          {
                            '@type': '@builder.io/sdk:Element',
                            '@version': 2,
                            id: 'builder-ed18f8e498ac413fbfff60e3be864133',
                            component: {
                              name: 'Core:Button',
                              options: {
                                text: 'ROMANCE NOVELS',
                              },
                            },
                            responsiveStyles: {
                              large: {
                                display: 'flex',
                                flexDirection: 'column',
                                alignItems: 'stretch',
                                position: 'relative',
                                flexShrink: '0',
                                boxSizing: 'border-box',
                                marginTop: '20px',
                                appearance: 'none',
                                paddingTop: '15px',
                                paddingBottom: '15px',
                                paddingLeft: '25px',
                                paddingRight: '25px',
                                backgroundColor: 'rgba(172, 38, 38, 1)',
                                color: 'white',
                                borderRadius: '24px',
                                textAlign: 'center',
                                cursor: 'pointer',
                                width: 'auto',
                                alignSelf: 'center',
                                fontWeight: '600',
                              },
                            },
                          },
                        ],
                        responsiveStyles: {
                          large: {
                            display: 'flex',
                            flexDirection: 'column',
                            alignItems: 'stretch',
                            position: 'relative',
                            flexShrink: '0',
                            boxSizing: 'border-box',
                            marginTop: 'auto',
                            height: 'auto',
                            paddingBottom: '30px',
                            marginBottom: 'auto',
                          },
                        },
                      },
                    ],
                    responsiveStyles: {
                      large: {
                        display: 'flex',
                        flexDirection: 'column',
                        alignItems: 'stretch',
                        position: 'relative',
                        flexShrink: '0',
                        boxSizing: 'border-box',
                        minHeight: '500px',
                        minWidth: '20px',
                        overflow: 'hidden',
                        width: '100%',
                      },
                    },
                  },
                ],
                query: [
                  {
                    '@type': '@builder.io/core:Query',
                    property: 'experiment',
                    operator: 'is',
                    value: ['B'],
                  },
                ],
                name: 'B',
              },
            ],
            previewingIndex: null,
          },
        },
        children: [
          {
            '@type': '@builder.io/sdk:Element',
            '@version': 2,
            id: 'builder-9b6eb50e9d444e4bba303089a5e2d6ff',
            component: {
              name: 'Image',
              options: {
                image:
                  'https://cdn.builder.io/api/v1/image/assets%2F802a1eea7c44430aa23d4b9c708d07ad%2Fc27867fc7fa44b949ce9881e92276e26?width=1880',
                backgroundSize: 'cover',
                backgroundPosition: 'center',
                lazy: false,
                aspectRatio: 0.285,
                sizes: '(max-width: 638px) 94vw, (max-width: 998px) 96vw, 135vw',
                height: 1253,
                width: 1880,
              },
            },
            children: [
              {
                '@type': '@builder.io/sdk:Element',
                '@version': 2,
                id: 'builder-2882f7fbbe0846aaa5f611df3f7f703c',
                children: [
                  {
                    '@type': '@builder.io/sdk:Element',
                    '@version': 2,
                    id: 'builder-e95d03ca02144e82ba85eb38ccaf8b57',
                    component: {
                      name: 'Text',
                      options: {
                        text: '<p>Default</p>',
                      },
                    },
                    responsiveStyles: {
                      large: {
                        display: 'flex',
                        flexDirection: 'column',
                        alignItems: 'stretch',
                        position: 'relative',
                        flexShrink: '0',
                        boxSizing: 'border-box',
                        marginLeft: '20px',
                        lineHeight: 'normal',
                        height: 'auto',
                        textAlign: 'center',
                        fontSize: '72px',
                        color: 'rgba(255, 255, 255, 1)',
                        textShadow: '1px 3px 3px rgba(0, 0, 0, 1)',
                      },
                      small: {
                        marginLeft: '0px',
                        fontSize: '52px',
                      },
                    },
                  },
                  {
                    '@type': '@builder.io/sdk:Element',
                    '@version': 2,
                    id: 'builder-a5242bac9ed74211b1c0f8d1141215cf',
                    component: {
                      name: 'Text',
                      options: {
                        text: '<p>Find Valentine Reads Here!</p>',
                      },
                    },
                    responsiveStyles: {
                      large: {
                        display: 'flex',
                        flexDirection: 'column',
                        alignItems: 'stretch',
                        position: 'relative',
                        flexShrink: '0',
                        boxSizing: 'border-box',
                        marginLeft: 'auto',
                        lineHeight: 'normal',
                        height: 'auto',
                        textAlign: 'center',
                        width: '20%',
                        marginRight: 'auto',
                        color: 'rgba(255, 255, 255, 1)',
                        textShadow: '1.5px 1px 3px rgba(0, 0, 0, 1)',
                      },
                      medium: {
                        width: '40%',
                      },
                      small: {
                        width: '70%',
                      },
                    },
                  },
                  {
                    '@type': '@builder.io/sdk:Element',
                    '@version': 2,
                    id: 'builder-29dc89277f05467e8f55e0b0c2c5df46',
                    component: {
                      name: 'Core:Button',
                      options: {
                        text: 'ROMANCE NOVELS',
                      },
                    },
                    responsiveStyles: {
                      large: {
                        display: 'flex',
                        flexDirection: 'column',
                        alignItems: 'stretch',
                        position: 'relative',
                        flexShrink: '0',
                        boxSizing: 'border-box',
                        marginTop: '20px',
                        appearance: 'none',
                        paddingTop: '15px',
                        paddingBottom: '15px',
                        paddingLeft: '25px',
                        paddingRight: '25px',
                        backgroundColor: 'rgba(172, 38, 38, 1)',
                        color: 'white',
                        borderRadius: '24px',
                        textAlign: 'center',
                        cursor: 'pointer',
                        width: 'auto',
                        alignSelf: 'center',
                        fontWeight: '600',
                      },
                    },
                  },
                ],
                responsiveStyles: {
                  large: {
                    display: 'flex',
                    flexDirection: 'column',
                    alignItems: 'stretch',
                    position: 'relative',
                    flexShrink: '0',
                    boxSizing: 'border-box',
                    marginTop: 'auto',
                    height: 'auto',
                    paddingBottom: '30px',
                    marginBottom: 'auto',
                  },
                },
              },
            ],
            responsiveStyles: {
              large: {
                display: 'flex',
                flexDirection: 'column',
                alignItems: 'stretch',
                position: 'relative',
                flexShrink: '0',
                boxSizing: 'border-box',
                minHeight: '500px',
                minWidth: '20px',
                overflow: 'hidden',
                width: '100%',
              },
            },
          },
        ],
        responsiveStyles: {
          large: {
            display: 'flex',
            flexDirection: 'column',
            position: 'relative',
            flexShrink: '0',
            boxSizing: 'border-box',
            marginTop: '20px',
          },
        },
      },
    ],
  },
  query: [
    {
      '@type': '@builder.io/core:Query',
      property: 'urlPath',
      value: '/personalization-container',
      operator: 'is',
    },
  ],
  name: 'Personalization test route',
  id: 'unique-id',
};
