export const VIDEO_CDN_URL =
  'https://cdn.builder.io/o/assets%2Fad30f9a246614faaa6a03374f83554c9%2Fb637ba8975044a8fa751c9386c281b77%2Fcompressed?apiKey=ad30f9a246614faaa6a03374f83554c9&token=b637ba8975044a8fa751c9386c281b77&alt=media&optimized=true';

export const CONTENT = {
  data: {
    title: 'Test',
    themeId: false,
    inputs: [],
    blocks: [
      {
        '@type': '@builder.io/sdk:Element',
        '@version': 2,
        id: 'builder-69d480c989bf4b1786d6c279757e8095',
        children: [
          {
            '@type': '@builder.io/sdk:Element',
            '@version': 2,
            id: 'builder-8cd920555733494d98e2260477f0303c',
            class: 'some-class',
            meta: { previousId: 'builder-042afd5b81c047aaaade0d13e8903c23' },
            component: {
              name: 'Video',
              options: {
                video: VIDEO_CDN_URL,
                autoPlay: true,
                controls: false,
                muted: true,
                loop: true,
                playsInline: true,
                fit: 'cover',
                preload: 'metadata',
                fitContent: false,
                position: 'center',
                aspectRatio: 1.3295,
                lazyLoad: true,
                height: null,
                width: null,
              },
            },
            children: [
              {
                '@type': '@builder.io/sdk:Element',
                '@version': 2,
                layerName: 'Hello everyone!!!',
                id: 'builder-3496ef3d87624c9dacb508b2650ed94e',
                component: { name: 'Text', options: { text: '<p>asfgasgasgasg some test</p>' } },
                responsiveStyles: {
                  large: {
                    display: 'flex',
                    flexDirection: 'column',
                    position: 'relative',
                    flexShrink: '0',
                    boxSizing: 'border-box',
                    marginTop: '20px',
                    lineHeight: 'normal',
                    height: 'auto',
                  },
                },
              },
            ],
            responsiveStyles: {
              large: {
                display: 'flex',
                flexDirection: 'column',
                position: 'relative',
                flexShrink: '0',
                boxSizing: 'border-box',
                marginTop: '100px',
                minHeight: '20px',
                minWidth: '20px',
                width: '100%',
                maxWidth: '152px',
                marginLeft: 'auto',
                marginRight: 'auto',
                marginBottom: 'auto',
                paddingBottom: '0px',
                paddingTop: '0px',
                paddingLeft: '0px',
              },
            },
          },
        ],
        responsiveStyles: {
          large: {
            display: 'flex',
            flexDirection: 'column',
            position: 'relative',
            flexShrink: '0',
            boxSizing: 'border-box',
            marginTop: '20px',
            height: '596px',
          },
        },
      },
      {
        '@type': '@builder.io/sdk:Element',
        '@version': 2,
        id: 'builder-7ec2c6c340b640159ace0d4d88081263',
        class: 'some-class',
        meta: { previousId: 'builder-6f71fccf52014a6e895d4812f304c91a' },
        component: {
          name: 'Video',
          options: {
            video: VIDEO_CDN_URL,
            autoPlay: true,
            controls: false,
            muted: true,
            loop: true,
            playsInline: true,
            fit: 'contain',
            preload: 'metadata',
            fitContent: false,
            position: 'center',
            aspectRatio: 0.1115,
            lazyLoad: true,
            height: null,
            width: null,
          },
        },
        children: [
          {
            '@type': '@builder.io/sdk:Element',
            '@version': 2,
            layerName: 'Hello everyone!!!',
            id: 'builder-7b41e5ca50f74389a66cd47858299722',
            meta: { previousId: 'builder-d0d730e84f9c47a380bab0152721cfdd' },
            component: { name: 'Text', options: { text: '<p>asfgasgasgasg some test</p>' } },
            responsiveStyles: {
              large: {
                display: 'flex',
                flexDirection: 'column',
                position: 'relative',
                flexShrink: '0',
                boxSizing: 'border-box',
                marginTop: '20px',
                lineHeight: 'normal',
                height: 'auto',
              },
            },
          },
        ],
        responsiveStyles: {
          large: {
            display: 'flex',
            flexDirection: 'column',
            position: 'relative',
            flexShrink: '0',
            boxSizing: 'border-box',
            marginTop: '78px',
            minHeight: '20px',
            minWidth: '20px',
            width: '100%',
            maxWidth: '1249px',
            marginLeft: 'auto',
            marginRight: 'auto',
            marginBottom: 'auto',
            paddingBottom: '0px',
            paddingTop: '0px',
            paddingLeft: '0px',
          },
        },
      },
      {
        '@type': '@builder.io/sdk:Element',
        '@version': 2,
        id: 'builder-5c71f9092b5f4084927cf56ae11874b9',
        class: 'some-class',
        meta: { previousId: 'builder-7ec2c6c340b640159ace0d4d88081263' },
        component: {
          name: 'Video',
          options: {
            video: VIDEO_CDN_URL,
            autoPlay: true,
            controls: true,
            muted: true,
            loop: true,
            playsInline: true,
            fit: 'cover',
            preload: 'metadata',
            fitContent: false,
            position: 'center',
            aspectRatio: 0.3498,
            lazyLoad: true,
            height: null,
            width: null,
          },
        },
        children: [
          {
            '@type': '@builder.io/sdk:Element',
            '@version': 2,
            layerName: 'Hello everyone!!!',
            id: 'builder-1d8b59cd087644f19b7811cb80bd108f',
            meta: { previousId: 'builder-7b41e5ca50f74389a66cd47858299722' },
            component: { name: 'Text', options: { text: '<p>asfgasgasgasg some test</p>' } },
            responsiveStyles: {
              large: {
                display: 'flex',
                flexDirection: 'column',
                position: 'relative',
                flexShrink: '0',
                boxSizing: 'border-box',
                marginTop: '20px',
                lineHeight: 'normal',
                height: 'auto',
              },
            },
          },
        ],
        responsiveStyles: {
          large: {
            display: 'flex',
            flexDirection: 'column',
            position: 'relative',
            flexShrink: '0',
            boxSizing: 'border-box',
            marginTop: '78px',
            minHeight: '20px',
            minWidth: '20px',
            width: '100%',
            maxWidth: '744px',
            marginRight: 'auto',
            marginBottom: 'auto',
            paddingBottom: '0px',
            paddingTop: '0px',
            paddingLeft: '0px',
          },
        },
      },
      {
        '@type': '@builder.io/sdk:Element',
        '@version': 2,
        tagName: 'a',
        id: 'builder-48b88c3a98a8495fb3b2ad658bef04c5',
        properties: { href: 'https://builder.io/', target: '_blank' },
        linkUrl: 'https://builder.io/',
        class: 'some-class',
        meta: { previousId: 'builder-e4b298b721d54f76ac3501f18eabd585' },
        component: {
          name: 'Video',
          options: {
            video: VIDEO_CDN_URL,
            autoPlay: true,
            controls: false,
            muted: true,
            loop: true,
            playsInline: true,
            fit: 'cover',
            preload: 'metadata',
            fitContent: false,
            position: 'center',
            aspectRatio: 1.3295,
            lazyLoad: true,
            height: null,
            width: null,
          },
        },
        children: [
          {
            '@type': '@builder.io/sdk:Element',
            '@version': 2,
            layerName: 'Hello everyone!!!',
            id: 'builder-cce2b748dd2f4f1289c6e2dfaada582a',
            meta: { previousId: 'builder-a02ee9763b724fc691cf89d970096fa0' },
            component: { name: 'Text', options: { text: '<p>asfgasgasgasg some test</p>' } },
            responsiveStyles: {
              large: {
                display: 'flex',
                flexDirection: 'column',
                position: 'relative',
                flexShrink: '0',
                boxSizing: 'border-box',
                marginTop: '20px',
                lineHeight: 'normal',
                height: 'auto',
              },
            },
          },
        ],
        responsiveStyles: {
          large: {
            display: 'flex',
            flexDirection: 'column',
            position: 'relative',
            flexShrink: '0',
            boxSizing: 'border-box',
            marginTop: '100px',
            minHeight: '20px',
            minWidth: '20px',
            width: '100%',
            maxWidth: '152px',
            marginLeft: 'auto',
            marginRight: 'auto',
            marginBottom: 'auto',
            paddingBottom: '0px',
            paddingTop: '0px',
            paddingLeft: '0px',
            cursor: 'pointer',
            pointerEvents: 'auto',
          },
        },
      },
    ],
  },
};
