// Generated by ACS2 SKILL - Ant International Security
// Local development only: no proxy, filesystem browsing, credentials or payment APIs.
const http = require('node:http');
const { mkdtemp, readFile, rm } = require('node:fs/promises');
const { tmpdir } = require('node:os');
const path = require('node:path');
const webpack = require('webpack');
const baseConfig = require('../webpack.config.js');
const pkg = require('../package.json');

const root = path.resolve(__dirname, '..');
const assets = new Map([
  [`/${pkg.output}`, 'application/javascript; charset=utf-8'],
  [`/${pkg.output}.LICENSE.txt`, 'text/plain; charset=utf-8'],
]);

async function startDevServer({ config = baseConfig, port = 1268, logger = console } = {}) {
  if (!Number.isInteger(port) || port < 0 || port > 65535) {
    throw new Error('Port must be an integer between 0 and 65535.');
  }
  const output = await mkdtemp(path.join(tmpdir(), 'antom-plugin-dev-'));
  let compiler;
  let closing;
  let state = 'building';
  let generation = 0;
  let buildGeneration = 0;
  let content = new Map();

  const server = http.createServer((request, response) => {
    const authority = request.headers.host?.toLowerCase();
    const actualPort = server.address()?.port;
    if (![ `localhost:${actualPort}`, `127.0.0.1:${actualPort}` ].includes(authority)) {
      response.writeHead(403).end();
      return;
    }
    // Deliberately match raw paths; never turn an HTTP path into a filesystem path.
    const pathname = request.url.split('?')[0];
    if (!assets.has(pathname)) {
      response.writeHead(404).end();
      return;
    }
    response.setHeader('Access-Control-Allow-Origin', '*');
    response.setHeader('Access-Control-Allow-Private-Network', 'true');
    response.setHeader('Access-Control-Allow-Methods', 'GET, HEAD, OPTIONS');
    response.setHeader('Cache-Control', 'no-store');
    response.setHeader('X-Content-Type-Options', 'nosniff');
    if (request.method === 'OPTIONS') {
      response.writeHead(204).end();
      return;
    }
    if (!['GET', 'HEAD'].includes(request.method)) {
      response.setHeader('Allow', 'GET, HEAD, OPTIONS');
      response.writeHead(405).end();
      return;
    }
    if (state !== 'ready') {
      response.setHeader('Retry-After', '1');
      response.writeHead(503).end();
      return;
    }
    const bytes = content.get(pathname);
    if (!bytes) {
      response.writeHead(404).end();
      return;
    }
    response.setHeader('Content-Type', assets.get(pathname));
    response.setHeader('Content-Length', bytes.length);
    response.writeHead(200).end(request.method === 'HEAD' ? undefined : bytes);
  });
  server.requestTimeout = 10_000;
  server.headersTimeout = 10_000;

  function close() {
    if (closing) return closing;
    state = 'closed';
    content.clear();
    closing = (async () => {
      const stopHttp = new Promise(resolve => server.close(resolve));
      server.closeAllConnections();
      try {
        await Promise.all([
          stopHttp,
          compiler && new Promise((resolve, reject) => {
            compiler.close(error => error ? reject(error) : resolve());
          }),
        ]);
      } finally {
        await rm(output, { recursive: true, force: true });
      }
    })();
    return closing;
  }

  try {
    compiler = webpack({
      ...config,
      context: config.context || root,
      mode: 'development',
      // Never overwrite the production dist/ bundle or its build metadata.
      output: { ...config.output, path: output },
    });
    compiler.hooks.invalid.tap('AntomLocalDevelopment', () => {
      generation += 1;
      if (state === 'closed') return;
      state = 'building';
      content.clear();
    });
    compiler.hooks.watchRun.tap('AntomLocalDevelopment', () => {
      buildGeneration = ++generation;
      if (state === 'closed') return;
      state = 'building';
      content.clear();
    });
    await new Promise((resolve, reject) => {
      server.once('error', reject);
      server.listen(port, '127.0.0.1', () => {
        server.removeListener('error', reject);
        resolve();
      });
    });
    compiler.watch(config.watchOptions || {}, (error, stats) => {
      if (state === 'closed') return;
      const current = buildGeneration;
      const fail = failure => {
        if (state === 'closed' || current !== generation) return;
        state = 'failed';
        content.clear();
        logger.error(failure);
      };
      if (error || stats.hasErrors()) {
        fail(error || stats.toString({ all: false, errors: true, errorDetails: true }));
        return;
      }
      // Publish a complete successful build atomically; never return partial/stale bytes.
      Promise.all([...assets.keys()].filter(name => stats.compilation.getAsset(name.slice(1)))
        .map(async name => [name, await readFile(path.join(output, name.slice(1)))]))
        .then(entries => {
          if (state === 'closed' || current !== generation) return;
          const next = new Map(entries);
          if (!next.has(`/${pkg.output}`)) throw new Error('Plugin bundle was not emitted.');
          content = next;
          state = 'ready';
          logger.log('Plugin rebuilt. Refresh Builder to load the latest bundle.');
        }).catch(fail);
    });
  } catch (error) {
    await close();
    throw error;
  }
  return { server, url: `http://127.0.0.1:${server.address().port}/${pkg.output}`, close };
}

if (require.main === module) {
  startDevServer().then(development => {
    console.log(`Antom local plugin: ${development.url}`);
    console.log('Automatic rebuilding is enabled; browser HMR/live reload is not provided.');
    const stop = () => development.close().catch(error => {
      console.error(error);
      process.exitCode = 1;
    });
    process.once('SIGINT', stop);
    process.once('SIGTERM', stop);
  }).catch(error => {
    console.error(error);
    process.exitCode = 1;
  });
}

module.exports = { startDevServer };
