name: Issue assignment

on:
    issues:
        types: [opened]

jobs:
    auto-assign:
        runs-on: ubuntu-latest
        steps:
            - name: 'Auto-assign issue'
              uses: pozil/auto-assign-issue@v1.1.0
              with:
                  assignees: mrkoreye,teleaziz,mandx,ca136,mhevery,manucorporat,adamdbradley,samijaber,Dkendal
                  numOfAssignee: 1
