---
name: Publish new generation SDKs

on:
  push:
    branches:
      - main
  # We allow manually dispatching workflow when needed. Most often, this will not be needed.
  workflow_dispatch:

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  publish-sdks:
    name: Publish new generation SDKs
    runs-on: ubuntu-latest

    steps:
      - name: Setup
        uses: actions/checkout@v3
        with:
          # need this custom token to run CI checks on the created PR
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'

      - name: 📥 Monorepo install
        uses: ./.github/actions/yarn-nm-install
        with:
          cache-node-modules: true
          cache-install-state: true

      - name: Create Release PR & Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          publish: yarn workspace @builder.io/sdks ci:release
          title: '📦 Publish SDKs'
          commit: '📦 Publish SDKs'
        env:
          # need this custom token to run CI checks on the created PR
          GITHUB_TOKEN: ${{ secrets.CUSTOM_GITHUB_TOKEN }}

          # probably don't need both of those, but it works!
          NPM_TOKEN: ${{ secrets.NPM_SDK_RELEASE_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_SDK_RELEASE_TOKEN }}

      # - name: Send Slack notification
      #   id: slack
      #   uses: slackapi/slack-github-action@v1.24.0
      #   with:
      #     payload: |
      #       { "publishedPackages": ${{ fromJson(steps.changesets.outputs.publishedPackages) }} }
      #   env:
      #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
