---
name: Publish new generation SDKs

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  publish-sdks:
    name: Publish new generation SDKs
    runs-on: ubuntu-latest

    steps:
      - name: Setup
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'

      - name: 📥 Monorepo install
        uses: ./.github/actions/yarn-nm-install
        with:
          cache-node-modules: true
          cache-install-state: true

      - name: Create Release Pull Request & Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          publish: yarn workspace @builder.io/sdks ci:release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_SDK_RELEASE_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_SDK_RELEASE_TOKEN }}
