---
name: React Native SDK test (Remote)

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

env:
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}

jobs:
  e2e-ios:
    name: React Native SDK iOS E2E tests
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
      - name: Setup
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - name: 📥 Monorepo install
        uses: ./.github/actions/yarn-nm-install
        with:
          cache-node-modules: true
          cache-install-state: true

      - name: Install Maestro
        run: curl -Ls "https://get.maestro.mobile.dev" | bash

      - name: Build and test
        run: yarn nx build-and-test:ios-remote @e2e/react-native
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_PAT_BUILD_AND_TEST }}
          NX_PUBLIC_EXPO_TOKEN: ${{ secrets.EXPO_PAT_BUILD_AND_TEST }}
